In [1]:
import pandas as pd
import numpy as np
import os

En primer lugar, ejecutamos el main.py de extracción de datos, para actualizar mantener los datos actualizados

In [2]:
actualizar = input("""¿Deseas actualizar los archivos de datos? (s/n)
         Ten en cuenta que puede tardar bastante en hacer las consultas, 
         por lo que si ya has cargado los datos una vez recomiendo no volver a hacerlo: """)

if actualizar=="s":
    %run main.py
elif actualizar=="n":
    print("No se han actualizado los archivos de datos.")

2026-08-22 18:36:59 | INFO    | Fuentes: Carto_provincias, INE_provincias, clima_aemet, datosgob, flujo_ine_localidad, flujo_ine_provincia, municipios_espana, turismo_oferta_osm
2026-08-22 18:36:59 | INFO    | --- FASE 1: Provincias (INE 2852) ---
2026-08-22 18:36:59 | INFO    | [INE_Pob_PROV] ▶ Descargando cifras oficiales de población por provincia (Tabla 2852)...
2026-08-22 18:36:59 | INFO    | [INE] ✔ Tabla 2852 descargada: 159 series.
2026-08-22 18:36:59 | INFO    | [INE_Pob_PROV] ✔ 52 provincias/ciudades autónomas procesadas correctamente.
2026-08-22 18:36:59 | INFO    | 52 filas -> INE_provincias.csv
2026-08-22 18:36:59 | INFO    | --- FASE 2: Municipios (INE 29005) ---
2026-08-22 18:36:59 | INFO    | [INE_Pob_MUN] ▶ Descargando cifras oficiales del padrón de todos los municipios de España (Tabla 29005)...
2026-08-22 18:37:02 | INFO    | [INE] ✔ Tabla 29005 descargada: 24414 series.
2026-08-22 18:37:02 | INFO    | [INE_Pob_MUN] ✔ 8132 municipios oficiales de España extraídos.
2026-08-22 18:37:02 | INFO    | 8132 filas -> municipios_espana.csv
2026-08-22 18:37:02 | INFO    | --- FASE 3: Flujos EOH Provincia (INE 2074) ---
2026-08-22 18:37:02 | INFO    | [INE_EOH_PROV] ▶ Descargando viajeros/pernoctaciones para todas las provincias y CCAA de España (últimos 12 períodos)...
2026-08-22 18:37:06 | INFO    | [INE] ✔ Tabla 2074 descargada: 420 series.
2026-08-22 18:37:06 | INFO    | [INE_EOH_PROV] ✔ 5040 filas | 69 ámbitos (todas las provincias y CCAA) | Tabla ID 2074
2026-08-22 18:37:06 | INFO    | 5040 filas -> flujo_ine_provincia.csv
2026-08-22 18:37:06 | INFO    | --- FASE 4: Flujos EOH Localidad (INE 2078) ---
2026-08-22 18:37:06 | INFO    | [INE_EOH_MUN] ▶ Descargando viajeros/pernoctaciones por localidad turística (últimos 12 períodos)...
2026-08-22 18:37:09 | INFO    | [INE] ✔ Tabla 2078 descargada: 552 series.
2026-08-22 18:37:09 | INFO    | [INE_EOH_MUN] ✔ 6610 filas | 113 localidades turísticas | Tabla ID 2078
2026-08-22 18:37:09 | INFO    | 6610 filas -> flujo_ine_localidad.csv
2026-08-22 18:37:09 | INFO    | --- FASE 5: Geocodificacion (CartoCiudad/IGN) ---

Geocodificando:   0%|          | 0/52 [00:00<?, ?it/s]

2026-08-22 18:37:11 | INFO    | [CartoCiudad] Vitoria-Gasteiz -> 01059

Geocodificando:   2%|▏         | 1/52 [00:01<01:14,  1.46s/it]

2026-08-22 18:37:13 | INFO    | [CartoCiudad] Albacete -> 02003

Geocodificando:   4%|▍         | 2/52 [00:03<01:34,  1.88s/it]

2026-08-22 18:37:15 | INFO    | [CartoCiudad] Alicante -> 03014

Geocodificando:   6%|▌         | 3/52 [00:05<01:26,  1.77s/it]

2026-08-22 18:37:17 | INFO    | [CartoCiudad] Almería -> 04013

Geocodificando:   8%|▊         | 4/52 [00:07<01:32,  1.93s/it]

2026-08-22 18:37:19 | INFO    | [CartoCiudad] Ávila -> 05019

Geocodificando:  10%|▉         | 5/52 [00:09<01:31,  1.94s/it]

2026-08-22 18:37:21 | INFO    | [CartoCiudad] Badajoz -> 06015

Geocodificando:  12%|█▏        | 6/52 [00:11<01:29,  1.94s/it]

2026-08-22 18:37:23 | INFO    | [CartoCiudad] Palma -> 35016

Geocodificando:  13%|█▎        | 7/52 [00:13<01:29,  2.00s/it]

2026-08-22 18:37:25 | INFO    | [CartoCiudad] Barcelona -> 08019

Geocodificando:  15%|█▌        | 8/52 [00:15<01:32,  2.09s/it]

2026-08-22 18:37:27 | INFO    | [CartoCiudad] Burgos -> 09059

Geocodificando:  17%|█▋        | 9/52 [00:17<01:28,  2.06s/it]

2026-08-22 18:37:29 | INFO    | [CartoCiudad] Cáceres -> 10037

Geocodificando:  19%|█▉        | 10/52 [00:19<01:25,  2.04s/it]

2026-08-22 18:37:31 | INFO    | [CartoCiudad] Cádiz -> 11012

Geocodificando:  21%|██        | 11/52 [00:21<01:24,  2.06s/it]

2026-08-22 18:37:33 | INFO    | [CartoCiudad] Castellón de la Plana -> 12040

Geocodificando:  23%|██▎       | 12/52 [00:23<01:14,  1.87s/it]

2026-08-22 18:37:35 | INFO    | [CartoCiudad] Ciudad Real -> 13034

Geocodificando:  25%|██▌       | 13/52 [00:25<01:16,  1.96s/it]

2026-08-22 18:37:37 | INFO    | [CartoCiudad] Córdoba -> 14021

Geocodificando:  27%|██▋       | 14/52 [00:27<01:15,  1.99s/it]

2026-08-22 18:37:39 | INFO    | [CartoCiudad] A Coruña -> 15030

Geocodificando:  29%|██▉       | 15/52 [00:29<01:11,  1.94s/it]

2026-08-22 18:37:41 | INFO    | [CartoCiudad] Cuenca -> 16078

Geocodificando:  31%|███       | 16/52 [00:31<01:10,  1.96s/it]

2026-08-22 18:37:43 | INFO    | [CartoCiudad] Girona -> 17079

Geocodificando:  33%|███▎      | 17/52 [00:33<01:09,  1.98s/it]

2026-08-22 18:37:45 | INFO    | [CartoCiudad] Granada -> 18087

Geocodificando:  35%|███▍      | 18/52 [00:35<01:12,  2.14s/it]

2026-08-22 18:37:47 | INFO    | [CartoCiudad] Guadalajara -> 19130

Geocodificando:  37%|███▋      | 19/52 [00:37<01:04,  1.95s/it]

2026-08-22 18:37:49 | INFO    | [CartoCiudad] Donostia/San Sebastián -> 20069

Geocodificando:  38%|███▊      | 20/52 [00:39<01:05,  2.05s/it]

2026-08-22 18:37:51 | INFO    | [CartoCiudad] Huelva -> 21041

Geocodificando:  40%|████      | 21/52 [00:41<00:59,  1.91s/it]

2026-08-22 18:37:53 | INFO    | [CartoCiudad] Huesca -> 22125

Geocodificando:  42%|████▏     | 22/52 [00:43<00:58,  1.95s/it]

2026-08-22 18:37:55 | INFO    | [CartoCiudad] Jaén -> 23050

Geocodificando:  44%|████▍     | 23/52 [00:45<00:56,  1.96s/it]

2026-08-22 18:37:57 | INFO    | [CartoCiudad] León -> 24089

Geocodificando:  46%|████▌     | 24/52 [00:47<00:58,  2.09s/it]

2026-08-22 18:37:59 | INFO    | [CartoCiudad] Lleida -> 25120

Geocodificando:  48%|████▊     | 25/52 [00:49<00:52,  1.94s/it]

2026-08-22 18:38:01 | INFO    | [CartoCiudad] Logroño -> 26089

Geocodificando:  50%|█████     | 26/52 [00:51<00:51,  1.96s/it]

2026-08-22 18:38:03 | INFO    | [CartoCiudad] Lugo -> 27028

Geocodificando:  52%|█████▏    | 27/52 [00:53<00:49,  1.98s/it]

2026-08-22 18:38:05 | INFO    | [CartoCiudad] Madrid -> 28079

Geocodificando:  54%|█████▍    | 28/52 [00:55<00:49,  2.06s/it]

2026-08-22 18:38:08 | INFO    | [CartoCiudad] Málaga -> 29067

Geocodificando:  56%|█████▌    | 29/52 [00:58<00:52,  2.27s/it]

2026-08-22 18:38:09 | INFO    | [CartoCiudad] Murcia -> 30030

Geocodificando:  58%|█████▊    | 30/52 [00:59<00:43,  1.99s/it]

2026-08-22 18:38:11 | INFO    | [CartoCiudad] Pamplona/Iruña -> 31201

Geocodificando:  60%|█████▉    | 31/52 [01:01<00:41,  1.99s/it]

2026-08-22 18:38:13 | INFO    | [CartoCiudad] Ourense -> 32054

Geocodificando:  62%|██████▏   | 32/52 [01:03<00:40,  2.01s/it]

2026-08-22 18:38:15 | INFO    | [CartoCiudad] Oviedo -> 33044

Geocodificando:  63%|██████▎   | 33/52 [01:05<00:38,  2.03s/it]

2026-08-22 18:38:17 | INFO    | [CartoCiudad] Palencia -> 34120

Geocodificando:  65%|██████▌   | 34/52 [01:07<00:35,  1.95s/it]

2026-08-22 18:38:19 | INFO    | [CartoCiudad] Las Palmas de Gran Canaria -> 35016

Geocodificando:  67%|██████▋   | 35/52 [01:09<00:33,  1.96s/it]

2026-08-22 18:38:21 | INFO    | [CartoCiudad] Pontevedra -> 36038

Geocodificando:  69%|██████▉   | 36/52 [01:11<00:31,  1.97s/it]

2026-08-22 18:38:24 | INFO    | [CartoCiudad] Salamanca -> 37274

Geocodificando:  71%|███████   | 37/52 [01:14<00:32,  2.14s/it]

2026-08-22 18:38:25 | INFO    | [CartoCiudad] Santa Cruz de Tenerife -> 38038

Geocodificando:  73%|███████▎  | 38/52 [01:15<00:27,  1.94s/it]

2026-08-22 18:38:28 | INFO    | [CartoCiudad] Santander -> 39075

Geocodificando:  75%|███████▌  | 39/52 [01:18<00:28,  2.18s/it]

2026-08-22 18:38:29 | INFO    | [CartoCiudad] Segovia -> 40194

Geocodificando:  77%|███████▋  | 40/52 [01:19<00:23,  1.92s/it]

2026-08-22 18:38:31 | INFO    | [CartoCiudad] Sevilla -> 41091

Geocodificando:  79%|███████▉  | 41/52 [01:21<00:21,  1.97s/it]

2026-08-22 18:38:33 | INFO    | [CartoCiudad] Soria -> 42173

Geocodificando:  81%|████████  | 42/52 [01:23<00:20,  2.00s/it]

2026-08-22 18:38:35 | INFO    | [CartoCiudad] Tarragona -> 43148

Geocodificando:  83%|████████▎ | 43/52 [01:25<00:17,  1.96s/it]

2026-08-22 18:38:37 | INFO    | [CartoCiudad] Teruel -> 44216

Geocodificando:  85%|████████▍ | 44/52 [01:27<00:15,  1.99s/it]

2026-08-22 18:38:40 | INFO    | [CartoCiudad] Toledo -> 45168

Geocodificando:  87%|████████▋ | 45/52 [01:30<00:15,  2.14s/it]

2026-08-22 18:38:41 | INFO    | [CartoCiudad] València -> 46250

Geocodificando:  88%|████████▊ | 46/52 [01:31<00:11,  1.97s/it]

2026-08-22 18:38:43 | INFO    | [CartoCiudad] Valladolid -> 47186

Geocodificando:  90%|█████████ | 47/52 [01:33<00:09,  1.92s/it]

2026-08-22 18:38:45 | INFO    | [CartoCiudad] Bilbao -> 48020

Geocodificando:  92%|█████████▏| 48/52 [01:35<00:07,  1.97s/it]

2026-08-22 18:38:47 | INFO    | [CartoCiudad] Zamora -> 49275

Geocodificando:  94%|█████████▍| 49/52 [01:37<00:05,  1.98s/it]

2026-08-22 18:38:49 | INFO    | [CartoCiudad] Zaragoza -> 50297

Geocodificando:  96%|█████████▌| 50/52 [01:39<00:04,  2.02s/it]

2026-08-22 18:38:51 | INFO    | [CartoCiudad] Ceuta -> 51001

Geocodificando:  98%|█████████▊| 51/52 [01:41<00:02,  2.05s/it]

2026-08-22 18:38:53 | INFO    | [CartoCiudad] Melilla -> 52001

Geocodificando: 100%|██████████| 52/52 [01:43<00:00,  2.00s/it]

2026-08-22 18:38:53 | INFO    | 52 filas -> Carto_provincias.csv
2026-08-22 18:38:53 | INFO    | --- FASE 6: POIs OSM ---

POIs OSM:   0%|          | 0/52 [00:00<?, ?it/s]

2026-08-22 18:39:03 | INFO    | [OSM] Vitoria-Gasteiz -> 302 POIs

POIs OSM:   2%|▏         | 1/52 [00:09<08:25,  9.91s/it]

2026-08-22 18:39:08 | INFO    | [OSM] Albacete -> 151 POIs

POIs OSM:   4%|▍         | 2/52 [00:14<05:42,  6.84s/it]

2026-08-22 18:39:17 | INFO    | [OSM] Alicante -> 605 POIs

POIs OSM:   6%|▌         | 3/52 [00:23<06:13,  7.62s/it]

2026-08-22 18:39:25 | INFO    | [OSM] Almería -> 22 POIs

POIs OSM:   8%|▊         | 4/52 [00:31<06:23,  7.98s/it]

2026-08-22 18:39:32 | INFO    | [OSM] Ávila -> 105 POIs

POIs OSM:  10%|▉         | 5/52 [00:38<05:53,  7.51s/it]

2026-08-22 18:39:40 | INFO    | [OSM] Badajoz -> 115 POIs

POIs OSM:  12%|█▏        | 6/52 [00:46<05:55,  7.74s/it]

2026-08-22 18:39:51 | INFO    | [OSM] Palma -> 789 POIs

POIs OSM:  13%|█▎        | 7/52 [00:57<06:34,  8.76s/it]

2026-08-22 18:40:03 | INFO    | [OSM] Barcelona -> 4750 POIs

POIs OSM:  15%|█▌        | 8/52 [01:09<07:15,  9.89s/it]

2026-08-22 18:40:18 | INFO    | [OSM] Fallback Nominatim para 'Burgos'
2026-08-22 18:40:24 | INFO    | [OSM] Burgos -> fallback OK

POIs OSM:  17%|█▋        | 9/52 [01:30<09:27, 13.20s/it]

2026-08-22 18:40:33 | INFO    | [OSM] Cáceres -> 152 POIs

POIs OSM:  19%|█▉        | 10/52 [01:39<08:21, 11.93s/it]

2026-08-22 18:40:46 | INFO    | [OSM] Cádiz -> 358 POIs

POIs OSM:  21%|██        | 11/52 [01:52<08:20, 12.21s/it]

2026-08-22 18:40:58 | INFO    | [OSM] Castellón de la Plana -> 249 POIs

POIs OSM:  23%|██▎       | 12/52 [02:04<08:13, 12.35s/it]

2026-08-22 18:41:11 | INFO    | [OSM] Ciudad Real -> 38 POIs

POIs OSM:  25%|██▌       | 13/52 [02:17<08:01, 12.35s/it]

2026-08-22 18:41:25 | INFO    | [OSM] Córdoba -> 497 POIs

POIs OSM:  27%|██▋       | 14/52 [02:32<08:18, 13.12s/it]

2026-08-22 18:41:40 | INFO    | [OSM] Fallback Nominatim para 'A Coruña'
2026-08-22 18:41:47 | INFO    | [OSM] A Coruña -> fallback OK

POIs OSM:  29%|██▉       | 15/52 [02:53<09:35, 15.55s/it]

2026-08-22 18:41:58 | INFO    | [OSM] Cuenca -> 130 POIs

POIs OSM:  31%|███       | 16/52 [03:04<08:37, 14.37s/it]

2026-08-22 18:42:14 | INFO    | [OSM] Fallback Nominatim para 'Girona'
2026-08-22 18:42:21 | INFO    | [OSM] Girona -> fallback OK

POIs OSM:  33%|███▎      | 17/52 [03:27<09:46, 16.75s/it]

2026-08-22 18:42:35 | INFO    | [OSM] Granada -> 792 POIs

POIs OSM:  35%|███▍      | 18/52 [03:41<09:07, 16.11s/it]

2026-08-22 18:42:50 | INFO    | [OSM] Fallback Nominatim para 'Guadalajara'
2026-08-22 18:42:56 | INFO    | [OSM] Guadalajara -> fallback OK

POIs OSM:  37%|███▋      | 19/52 [04:02<09:37, 17.49s/it]

2026-08-22 18:43:08 | INFO    | [OSM] Donostia/San Sebastián -> 584 POIs

POIs OSM:  38%|███▊      | 20/52 [04:14<08:26, 15.84s/it]

2026-08-22 18:43:21 | INFO    | [OSM] Huelva -> 114 POIs

POIs OSM:  40%|████      | 21/52 [04:27<07:42, 14.93s/it]

2026-08-22 18:43:32 | INFO    | [OSM] Huesca -> 21 POIs

POIs OSM:  42%|████▏     | 22/52 [04:38<06:52, 13.73s/it]

2026-08-22 18:43:48 | INFO    | [OSM] Jaén -> 166 POIs

POIs OSM:  44%|████▍     | 23/52 [04:54<07:00, 14.50s/it]

2026-08-22 18:44:02 | INFO    | [OSM] León -> 3 POIs

POIs OSM:  46%|████▌     | 24/52 [05:08<06:45, 14.48s/it]

2026-08-22 18:44:17 | INFO    | [OSM] Fallback Nominatim para 'Lleida'
2026-08-22 18:44:22 | INFO    | [OSM] Lleida -> fallback OK

POIs OSM:  48%|████▊     | 25/52 [05:28<07:10, 15.94s/it]

2026-08-22 18:44:36 | INFO    | [OSM] Fallback Nominatim para 'Logroño'
2026-08-22 18:44:40 | INFO    | [OSM] Logroño -> fallback OK

POIs OSM:  50%|█████     | 26/52 [05:46<07:15, 16.76s/it]

2026-08-22 18:44:55 | INFO    | [OSM] Fallback Nominatim para 'Lugo'
2026-08-22 18:45:00 | INFO    | [OSM] Lugo -> fallback OK

POIs OSM:  52%|█████▏    | 27/52 [06:06<07:23, 17.74s/it]

2026-08-22 18:45:12 | INFO    | [OSM] Fallback Nominatim para 'Madrid'
2026-08-22 18:45:18 | INFO    | [OSM] Madrid -> fallback OK

POIs OSM:  54%|█████▍    | 28/52 [06:24<07:07, 17.79s/it]

2026-08-22 18:45:33 | INFO    | [OSM] Fallback Nominatim para 'Málaga'
2026-08-22 18:45:40 | INFO    | [OSM] Málaga -> fallback OK

POIs OSM:  56%|█████▌    | 29/52 [06:46<07:18, 19.08s/it]

2026-08-22 18:45:55 | INFO    | [OSM] Fallback Nominatim para 'Murcia'
2026-08-22 18:45:59 | INFO    | [OSM] Murcia -> fallback OK

POIs OSM:  58%|█████▊    | 30/52 [07:05<06:59, 19.05s/it]

2026-08-22 18:46:14 | INFO    | [OSM] Fallback Nominatim para 'Pamplona/Iruña'
2026-08-22 18:46:19 | INFO    | [OSM] Pamplona/Iruña -> fallback OK

POIs OSM:  60%|█████▉    | 31/52 [07:25<06:45, 19.32s/it]

2026-08-22 18:46:34 | INFO    | [OSM] Fallback Nominatim para 'Ourense'
2026-08-22 18:46:39 | INFO    | [OSM] Ourense -> fallback OK

POIs OSM:  62%|██████▏   | 32/52 [07:45<06:25, 19.28s/it]

2026-08-22 18:46:52 | INFO    | [OSM] Oviedo -> 462 POIs

POIs OSM:  63%|██████▎   | 33/52 [07:58<05:31, 17.44s/it]

2026-08-22 18:47:05 | INFO    | [OSM] Palencia -> 9 POIs

POIs OSM:  65%|██████▌   | 34/52 [08:11<04:49, 16.10s/it]

2026-08-22 18:47:16 | INFO    | [OSM] Las Palmas de Gran Canaria -> 584 POIs

POIs OSM:  67%|██████▋   | 35/52 [08:22<04:11, 14.79s/it]

2026-08-22 18:47:31 | INFO    | [OSM] Fallback Nominatim para 'Pontevedra'
2026-08-22 18:47:36 | INFO    | [OSM] Pontevedra -> fallback OK

POIs OSM:  69%|██████▉   | 36/52 [08:42<04:18, 16.19s/it]

2026-08-22 18:47:50 | INFO    | [OSM] Salamanca -> 335 POIs

POIs OSM:  71%|███████   | 37/52 [08:56<03:54, 15.61s/it]

2026-08-22 18:48:05 | INFO    | [OSM] Fallback Nominatim para 'Santa Cruz de Tenerife'
2026-08-22 18:48:10 | INFO    | [OSM] Santa Cruz de Tenerife -> fallback OK

POIs OSM:  73%|███████▎  | 38/52 [09:16<03:56, 16.91s/it]

2026-08-22 18:48:25 | INFO    | [OSM] Santander -> 427 POIs

POIs OSM:  75%|███████▌  | 39/52 [09:31<03:30, 16.22s/it]

2026-08-22 18:48:40 | INFO    | [OSM] Fallback Nominatim para 'Segovia'
2026-08-22 18:48:46 | INFO    | [OSM] Segovia -> fallback OK

POIs OSM:  77%|███████▋  | 40/52 [09:52<03:31, 17.65s/it]

2026-08-22 18:49:00 | INFO    | [OSM] Fallback Nominatim para 'Sevilla'
2026-08-22 18:49:06 | INFO    | [OSM] Sevilla -> fallback OK

POIs OSM:  79%|███████▉  | 41/52 [10:12<03:23, 18.49s/it]

2026-08-22 18:49:21 | INFO    | [OSM] Fallback Nominatim para 'Soria'
2026-08-22 18:49:25 | INFO    | [OSM] Soria -> fallback OK

POIs OSM:  81%|████████  | 42/52 [10:31<03:06, 18.68s/it]

2026-08-22 18:49:38 | INFO    | [OSM] Tarragona -> 264 POIs

POIs OSM:  83%|████████▎ | 43/52 [10:45<02:33, 17.05s/it]

2026-08-22 18:49:50 | INFO    | [OSM] Teruel -> 11 POIs

POIs OSM:  85%|████████▍ | 44/52 [10:56<02:03, 15.44s/it]

2026-08-22 18:50:05 | INFO    | [OSM] Fallback Nominatim para 'Toledo'
2026-08-22 18:50:10 | INFO    | [OSM] Toledo -> fallback OK

POIs OSM:  87%|████████▋ | 45/52 [11:16<01:57, 16.84s/it]

2026-08-22 18:50:22 | INFO    | [OSM] València -> 1679 POIs

POIs OSM:  88%|████████▊ | 46/52 [11:28<01:32, 15.41s/it]

2026-08-22 18:50:37 | INFO    | [OSM] Fallback Nominatim para 'Valladolid'
2026-08-22 18:50:42 | INFO    | [OSM] Valladolid -> fallback OK

POIs OSM:  90%|█████████ | 47/52 [11:48<01:24, 16.81s/it]

2026-08-22 18:50:56 | INFO    | [OSM] Fallback Nominatim para 'Bilbao'
2026-08-22 18:51:03 | INFO    | [OSM] Bilbao -> fallback OK

POIs OSM:  92%|█████████▏| 48/52 [12:09<01:11, 17.81s/it]

2026-08-22 18:51:17 | INFO    | [OSM] Zamora -> 1 POIs

POIs OSM:  94%|█████████▍| 49/52 [12:23<00:50, 16.74s/it]

2026-08-22 18:51:29 | INFO    | [OSM] Zaragoza -> 955 POIs

POIs OSM:  96%|█████████▌| 50/52 [12:35<00:30, 15.34s/it]

2026-08-22 18:51:43 | INFO    | [OSM] Ceuta -> 59 POIs

POIs OSM:  98%|█████████▊| 51/52 [12:49<00:14, 14.90s/it]

2026-08-22 18:51:52 | INFO    | [OSM] Melilla -> 62 POIs

POIs OSM: 100%|██████████| 52/52 [12:59<00:00, 14.98s/it]

2026-08-22 18:51:52 | INFO    | 52 filas -> oferta_osm.csv
2026-08-22 18:51:52 | INFO    | --- FASE 7: AEMET OpenData ---

2026-08-22 18:51:53 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/01059, esperando antes de reintentar...
2026-08-22 18:52:10 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/09059, esperando antes de reintentar...
2026-08-22 18:52:17 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/09059, esperando antes de reintentar...
2026-08-22 18:52:24 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/09059, esperando antes de reintentar...
2026-08-22 18:52:33 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/09059, esperando antes de reintentar...
2026-08-22 18:52:38 | WARNING | [AEMET] Error INE 09059: 429 Client Error: Too Many Requests for url: https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/09059
2026-08-22 18:52:39 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/10037, esperando antes de reintentar...
2026-08-22 18:52:46 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/10037, esperando antes de reintentar...
2026-08-22 18:52:53 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/10037, esperando antes de reintentar...
2026-08-22 18:53:12 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/18087, esperando antes de reintentar...
2026-08-22 18:53:19 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/18087, esperando antes de reintentar...
2026-08-22 18:53:27 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/18087, esperando antes de reintentar...
2026-08-22 18:53:36 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/18087, esperando antes de reintentar...
2026-08-22 18:53:41 | WARNING | [AEMET] Error INE 18087: 429 Client Error: Too Many Requests for url: https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/18087
2026-08-22 18:53:41 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/19130, esperando antes de reintentar...
2026-08-22 18:53:48 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/19130, esperando antes de reintentar...
2026-08-22 18:53:56 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/19130, esperando antes de reintentar...
2026-08-22 18:54:15 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/27028, esperando antes de reintentar...
2026-08-22 18:54:22 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/27028, esperando antes de reintentar...
2026-08-22 18:54:29 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/27028, esperando antes de reintentar...
2026-08-22 18:54:38 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/27028, esperando antes de reintentar...
2026-08-22 18:54:43 | WARNING | [AEMET] Error INE 27028: 429 Client Error: Too Many Requests for url: https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/27028
2026-08-22 18:54:44 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/28079, esperando antes de reintentar...
2026-08-22 18:54:51 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/28079, esperando antes de reintentar...
2026-08-22 18:54:58 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/28079, esperando antes de reintentar...
2026-08-22 18:55:17 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/36038, esperando antes de reintentar...
2026-08-22 18:55:24 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/36038, esperando antes de reintentar...
2026-08-22 18:55:32 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/36038, esperando antes de reintentar...
2026-08-22 18:55:41 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/36038, esperando antes de reintentar...
2026-08-22 18:55:46 | WARNING | [AEMET] Error INE 36038: 429 Client Error: Too Many Requests for url: https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/36038
2026-08-22 18:55:46 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/37274, esperando antes de reintentar...
2026-08-22 18:55:53 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/37274, esperando antes de reintentar...
2026-08-22 18:56:10 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/45168, esperando antes de reintentar...
2026-08-22 18:56:18 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/45168, esperando antes de reintentar...
2026-08-22 18:56:25 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/45168, esperando antes de reintentar...
2026-08-22 18:56:34 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/45168, esperando antes de reintentar...
2026-08-22 18:56:39 | WARNING | [AEMET] Error INE 45168: 429 Client Error: Too Many Requests for url: https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/45168
2026-08-22 18:56:39 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/46250, esperando antes de reintentar...
2026-08-22 18:56:47 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/46250, esperando antes de reintentar...
2026-08-22 18:56:54 | WARNING | Rate limit alcanzado en https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/46250, esperando antes de reintentar...
2026-08-22 18:57:11 | INFO    | 329 filas -> clima_aemet.csv
2026-08-22 18:57:11 | INFO    | --- FASE 8: datos.gob.es ---
2026-08-22 18:57:11 | INFO    | [DatosGob] ▶ Buscando datasets relacionados con 'turismo' en el catálogo nacional...
2026-08-22 18:57:13 | INFO    | [DatosGob] ✔ 'turismo' → 0 recursos encontrados en el catálogo.
2026-08-22 18:57:13 | INFO    | [DatosGob] ▶ Buscando datasets relacionados con 'ocupación hotelera' en el catálogo nacional...
2026-08-22 18:57:13 | INFO    | [DatosGob] ✔ 'ocupación hotelera' → 0 recursos encontrados en el catálogo.
2026-08-22 18:57:13 | INFO    | [DatosGob] ▶ Buscando datasets relacionados con 'turismo rural' en el catálogo nacional...
2026-08-22 18:57:13 | INFO    | [DatosGob] ✔ 'turismo rural' → 0 recursos encontrados en el catálogo.
2026-08-22 18:57:13 | INFO    | [DatosGob] ▶ Buscando datasets relacionados con 'alojamientos turísticos' en el catálogo nacional...
2026-08-22 18:57:15 | INFO    | [DatosGob] ✔ 'alojamientos turísticos' → 0 recursos encontrados en el catálogo.
2026-08-22 18:57:15 | INFO    | Reporte: 0 fallos -> reporte_fallos.csv
2026-08-22 18:57:15 | INFO    | Pipeline completado. CSV en: C:\Users\Manuel Santos\Escritorio\MASTER\TFM - TUI\Antigravity-Prueba\data\processed

In [3]:
localidades = pd.read_csv('data/processed/flujo_ine_localidad.csv', sep=',', encoding='UTF-8')
provincias = pd.read_csv('data/processed/flujo_ine_provincia.csv', sep=',', encoding='UTF-8')
localidades_data = pd.read_csv('data/processed/Carto_provincias.csv', sep=',', encoding='UTF-8')
OpenStreetDf = pd.read_csv('data/processed/oferta_osm.csv', sep=',', encoding='UTF-8')
provincias_data = pd.read_csv('data/processed/municipios_espana.csv', sep=',', encoding='UTF-8')
clima_df = pd.read_csv('data/processed/clima_aemet.csv', sep=',', encoding='UTF-8')

In [4]:
localidades.head()

,INE_EOH_MUN.punto_turistico,INE_EOH_MUN.indicador,INE_EOH_MUN.residencia,INE_EOH_MUN.nombre_serie_completo,INE_EOH_MUN.cod_serie,INE_EOH_MUN.anio,INE_EOH_MUN.periodo,INE_EOH_MUN.valor,INE_EOH_MUN.fuente,INE_EOH_MUN.tabla_id,_meta.fecha_extraccion
0,Vitoria-Gastéiz,viajeros,Residentes en España,Nacional. Viajeros. Vitoria-Gastéiz. Residente...,EOT2611,2026,NaN,18734.0,INE_EOH_MUN,2078,2026-08-22T16:37:09.911046
1,Vitoria-Gastéiz,viajeros,Residentes en España,Nacional. Viajeros. Vitoria-Gastéiz. Residente...,EOT2611,2026,NaN,19464.0,INE_EOH_MUN,2078,2026-08-22T16:37:09.911046
2,Vitoria-Gastéiz,viajeros,Residentes en España,Nacional. Viajeros. Vitoria-Gastéiz. Residente...,EOT2611,2026,NaN,20574.0,INE_EOH_MUN,2078,2026-08-22T16:37:09.911046
3,Vitoria-Gastéiz,viajeros,Residentes en España,Nacional. Viajeros. Vitoria-Gastéiz. Residente...,EOT2611,2026,NaN,21012.0,INE_EOH_MUN,2078,2026-08-22T16:37:09.911046
4,Vitoria-Gastéiz,viajeros,Residentes en España,Nacional. Viajeros. Vitoria-Gastéiz. Residente...,EOT2611,2026,NaN,20189.0,INE_EOH_MUN,2078,2026-08-22T16:37:09.911046

In [5]:
localidades_data.head()

,CartoCiudad.cod_ine,CartoCiudad.nombre_municipio,CartoCiudad.provincia,CartoCiudad.ccaa,CartoCiudad.latitud,CartoCiudad.longitud,_meta.fuente_geocod,_meta.fecha_extraccion,_meta.cod_ine_clave,_meta.nombre_municipio
0,1059,Vitoria-Gasteiz,Araba/Álava,País Vasco/Euskadi,42.850584,-2.661450,CartoCiudad+IGN,2026-08-22T16:37:11.517729,1059,Vitoria-Gasteiz
1,2003,Albacete,Albacete,Castilla-La Mancha,38.995092,-1.855915,CartoCiudad+IGN,2026-08-22T16:37:13.692689,2003,Albacete
2,3014,Alacant/Alicante,Alacant/Alicante,Comunitat Valenciana,38.343637,-0.488171,CartoCiudad+IGN,2026-08-22T16:37:15.325393,3014,Alicante
3,4013,Almería,Almería,Andalucía,36.868574,-2.312028,CartoCiudad+IGN,2026-08-22T16:37:17.494072,4013,Almería
4,5019,Ávila,Ávila,Castilla y León,40.657195,-4.662668,CartoCiudad+IGN,2026-08-22T16:37:19.457436,5019,Ávila

In [6]:
provincias[provincias['INE_EOH_PROV.indicador']=='Viajero'].head()

,INE_EOH_PROV.ambito,INE_EOH_PROV.indicador,INE_EOH_PROV.residencia,INE_EOH_PROV.nombre_serie_completo,INE_EOH_PROV.cod_serie,INE_EOH_PROV.anio,INE_EOH_PROV.periodo,INE_EOH_PROV.valor,INE_EOH_PROV.fuente,INE_EOH_PROV.tabla_id,_meta.fecha_extraccion
1080,Asturias,Viajero,Total categorías,Asturias. Viajero. Total categorías. Total. Da...,EOT22203,2026,NaN,251471.0,INE_EOH_PROV,2074,2026-08-22T16:37:06.275965
1081,Asturias,Viajero,Total categorías,Asturias. Viajero. Total categorías. Total. Da...,EOT22203,2026,NaN,206637.0,INE_EOH_PROV,2074,2026-08-22T16:37:06.275965
1082,Asturias,Viajero,Total categorías,Asturias. Viajero. Total categorías. Total. Da...,EOT22203,2026,NaN,175443.0,INE_EOH_PROV,2074,2026-08-22T16:37:06.275965
1083,Asturias,Viajero,Total categorías,Asturias. Viajero. Total categorías. Total. Da...,EOT22203,2026,NaN,147543.0,INE_EOH_PROV,2074,2026-08-22T16:37:06.275965
1084,Asturias,Viajero,Total categorías,Asturias. Viajero. Total categorías. Total. Da...,EOT22203,2026,NaN,113361.0,INE_EOH_PROV,2074,2026-08-22T16:37:06.275965

In [7]:
provincias_data.head()

,INE_Pob_MUN.nombre_municipio,INE_Pob_MUN.poblacion_oficial,INE_Pob_MUN.anio,INE_Pob_MUN.cod_serie,INE_Pob_MUN.nombre_serie_completo,INE_Pob_MUN.fuente,_meta.fecha_extraccion
0,Ababuj,73.0,2025,DPOP19723,Ababuj. Total. Total habitantes. Personas.,INE_Padron_Tabla_29005,2026-08-22T16:37:02.632217
1,Abades,849.0,2025,DPOP17671,Abades. Total. Total habitantes. Personas.,INE_Padron_Tabla_29005,2026-08-22T16:37:02.632217
2,Abadía,337.0,2025,DPOP4663,Abadía. Total. Total habitantes. Personas.,INE_Padron_Tabla_29005,2026-08-22T16:37:02.632217
3,Abadín,2239.0,2025,DPOP12721,Abadín. Total. Total habitantes. Personas.,INE_Padron_Tabla_29005,2026-08-22T16:37:02.632217
4,Abadiño,7768.0,2025,DPOP22525,Abadiño. Total. Total habitantes. Personas.,INE_Padron_Tabla_29005,2026-08-22T16:37:02.632217

In [8]:
OpenStreetDf.head()

,OSM_Overpass.num_hoteles,OSM_Overpass.num_restaurantes,OSM_Overpass.num_atracciones,OSM_Overpass.num_museos,OSM_Overpass.fuente,OSM_Overpass.fecha_extraccion,_meta.cod_ine_clave,_meta.nombre_municipio
0,31,245,11,15,Overpass (maps.mail.ru),2026-08-22T16:39:03.846868,1059,Vitoria-Gasteiz
1,11,132,2,6,Overpass (overpass-api.de),2026-08-22T16:39:08.542340,2003,Albacete
2,55,523,14,13,Overpass (maps.mail.ru),2026-08-22T16:39:17.095177,3014,Alicante
3,5,16,1,0,Overpass (maps.mail.ru),2026-08-22T16:39:25.619128,4013,Almería
4,20,63,14,8,Overpass (overpass-api.de),2026-08-22T16:39:32.303331,5019,Ávila