In [25]:
import pandas as pd
import numpy as np
import os

En primer lugar, ejecutamos el main.py de extracción de datos, para actualizar mantener los datos actualizados

In [26]:
actualizar = input("""¿Deseas actualizar los archivos de datos? (s/n)
         Ten en cuenta que puede tardar bastante en hacer las consultas, 
         por lo que si ya has cargado los datos una vez recomiendo no volver a hacerlo: """)

if actualizar=="s":
    %run main.py
elif actualizar=="n":
    print("No se han actualizado los archivos de datos.")

2026-08-21 18:44:29 | INFO    |
2026-08-21 18:44:29 | INFO    | =================================================================
2026-08-21 18:44:29 | INFO    |   FASE 0 · Inicialización del pipeline (Ámbito: España Completa)
2026-08-21 18:44:29 | INFO    | =================================================================
2026-08-21 18:44:29 | INFO    | Log de sesión → C:\Users\Manuel Santos\Escritorio\MASTER\TFM - TUI\Antigravity-Prueba\data\logs\log_sesion_20260821_184429.txt
2026-08-21 18:44:29 | INFO    | Fuentes activas: datosgob, flujo_ine_localidad, flujo_ine_provincia, localidades, municipios_espana, provincias, tripadvisor, turismo_oferta_osm
2026-08-21 18:44:29 | INFO    | Períodos históricos INE a descargar: 12 meses
2026-08-21 18:44:29 | INFO    |
2026-08-21 18:44:29 | INFO    | =================================================================
2026-08-21 18:44:29 | INFO    |   FASE 1 · Maestro de las 52 Provincias y Ciudades Autónomas de España (INE Tabla 2852)
2026-08-21 18:44:29 | INFO    | =================================================================
2026-08-21 18:44:29 | INFO    | [INE_Pob_PROV] ▶ Descargando cifras oficiales de población por provincia (Tabla 2852)...
2026-08-21 18:44:29 | INFO    | [INE] ✔ Tabla 2852 descargada: 159 series.
2026-08-21 18:44:29 | INFO    | [INE_Pob_PROV] ✔ 52 provincias/ciudades autónomas procesadas correctamente.
2026-08-21 18:44:29 | INFO    | [csv_writer] ✔  52 filas guardadas → provincias.csv  [columnas: INE_Pob_PROV.provincia, INE_Pob_PROV.poblacion_total, INE_Pob_PROV.anio, INE_Pob_PROV.cod_serie, INE_Pob_PROV.nombre_serie_completo, INE_Pob_PROV.fuente, _meta.fecha_extraccion, _meta.cod_prov, _meta.capital, _meta.ccaa]
2026-08-21 18:44:29 | INFO    |
2026-08-21 18:44:29 | INFO    | =================================================================
2026-08-21 18:44:29 | INFO    |   FASE 2 · Censo Oficial de los 8.138 Municipios de España (INE Tabla 29005)
2026-08-21 18:44:29 | INFO    | =================================================================
2026-08-21 18:44:29 | INFO    | [INE_Pob_MUN] ▶ Descargando cifras oficiales del padrón de todos los municipios de España (Tabla 29005)...
2026-08-21 18:44:32 | INFO    | [INE] ✔ Tabla 29005 descargada: 24414 series.
2026-08-21 18:44:32 | INFO    | [INE_Pob_MUN] ✔ 8132 municipios oficiales de España extraídos.
2026-08-21 18:44:32 | INFO    | [csv_writer] ✔  8132 filas guardadas → municipios_espana.csv  [columnas: INE_Pob_MUN.nombre_municipio, INE_Pob_MUN.poblacion_oficial, INE_Pob_MUN.anio, INE_Pob_MUN.cod_serie, INE_Pob_MUN.nombre_serie_completo, INE_Pob_MUN.fuente, _meta.fecha_extraccion]
2026-08-21 18:44:32 | INFO    |
2026-08-21 18:44:32 | INFO    | =================================================================
2026-08-21 18:44:32 | INFO    |   FASE 3 · Flujos Turísticos EOH por Provincias y CCAA de España (INE Tabla 2074)
2026-08-21 18:44:32 | INFO    | =================================================================
2026-08-21 18:44:32 | INFO    | [INE_EOH_PROV] ▶ Descargando viajeros/pernoctaciones para todas las provincias y CCAA de España (últimos 12 períodos)...
2026-08-21 18:44:35 | INFO    | [INE] ✔ Tabla 2074 descargada: 420 series.
2026-08-21 18:44:35 | INFO    | [INE_EOH_PROV] ✔ 5040 filas | 69 ámbitos (todas las provincias y CCAA) | Tabla ID 2074
2026-08-21 18:44:35 | INFO    | [csv_writer] ✔  5040 filas guardadas → flujo_ine_provincia.csv  [columnas: INE_EOH_PROV.ambito, INE_EOH_PROV.indicador, INE_EOH_PROV.residencia, INE_EOH_PROV.nombre_serie_completo, INE_EOH_PROV.cod_serie, INE_EOH_PROV.anio, INE_EOH_PROV.periodo, INE_EOH_PROV.valor, INE_EOH_PROV.fuente, INE_EOH_PROV.tabla_id, _meta.fecha_extraccion]
2026-08-21 18:44:35 | INFO    |
2026-08-21 18:44:35 | INFO    | =================================================================
2026-08-21 18:44:35 | INFO    |   FASE 4 · Flujos Turísticos EOH por Localidad Turística (113 Puntos) (INE Tabla 2078)
2026-08-21 18:44:35 | INFO    | =================================================================
2026-08-21 18:44:35 | INFO    | [INE_EOH_MUN] ▶ Descargando viajeros/pernoctaciones por localidad turística (últimos 12 períodos)...
2026-08-21 18:44:39 | INFO    | [INE] ✔ Tabla 2078 descargada: 552 series.
2026-08-21 18:44:39 | INFO    | [INE_EOH_MUN] ✔ 6610 filas | 113 localidades turísticas | Tabla ID 2078
2026-08-21 18:44:39 | INFO    | [csv_writer] ✔  6610 filas guardadas → flujo_ine_localidad.csv  [columnas: INE_EOH_MUN.punto_turistico, INE_EOH_MUN.indicador, INE_EOH_MUN.residencia, INE_EOH_MUN.nombre_serie_completo, INE_EOH_MUN.cod_serie, INE_EOH_MUN.anio, INE_EOH_MUN.periodo, INE_EOH_MUN.valor, INE_EOH_MUN.fuente, INE_EOH_MUN.tabla_id, _meta.fecha_extraccion]
2026-08-21 18:44:39 | INFO    |
2026-08-21 18:44:39 | INFO    | =================================================================
2026-08-21 18:44:39 | INFO    |   FASE 5 · Geocodificación oficial CartoCiudad/IGN de Capitales y Puntos Clave
2026-08-21 18:44:39 | INFO    | =================================================================

Geocodificando Provincias:   0%|          | 0/52 [00:00<?, ?it/s]

2026-08-21 18:44:40 | INFO    | [CartoCiudad] ✔ Vitoria-Gasteiz → cod_ine=01059, prov=Araba/Álava, lat=42.8506, lon=-2.6614

Geocodificando Provincias:   2%|▏         | 1/52 [00:01<01:03,  1.24s/it]

2026-08-21 18:44:42 | INFO    | [CartoCiudad] ✔ Albacete → cod_ine=02003, prov=Albacete, lat=38.9951, lon=-1.8559

Geocodificando Provincias:   4%|▍         | 2/52 [00:03<01:17,  1.55s/it]

2026-08-21 18:44:44 | INFO    | [CartoCiudad] ✔ Alicante → cod_ine=03014, prov=Alacant/Alicante, lat=38.3436, lon=-0.4882

Geocodificando Provincias:   6%|▌         | 3/52 [00:05<01:26,  1.76s/it]

2026-08-21 18:44:46 | INFO    | [CartoCiudad] ✔ Almería → cod_ine=04013, prov=Almería, lat=36.8686, lon=-2.3120

Geocodificando Provincias:   8%|▊         | 4/52 [00:07<01:28,  1.85s/it]

2026-08-21 18:44:48 | INFO    | [CartoCiudad] ✔ Ávila → cod_ine=05019, prov=Ávila, lat=40.6572, lon=-4.6627

Geocodificando Provincias:  10%|▉         | 5/52 [00:09<01:29,  1.91s/it]

2026-08-21 18:44:50 | INFO    | [CartoCiudad] ✔ Badajoz → cod_ine=06015, prov=Badajoz, lat=38.8782, lon=-6.9701

Geocodificando Provincias:  12%|█▏        | 6/52 [00:11<01:29,  1.94s/it]

2026-08-21 18:44:52 | INFO    | [CartoCiudad] ✔ Palma → cod_ine=35016, prov=Las Palmas, lat=39.5696, lon=2.6501

Geocodificando Provincias:  13%|█▎        | 7/52 [00:13<01:28,  1.96s/it]

2026-08-21 18:44:54 | INFO    | [CartoCiudad] ✔ Barcelona → cod_ine=08019, prov=Barcelona, lat=41.3826, lon=2.1771

Geocodificando Provincias:  15%|█▌        | 8/52 [00:15<01:26,  1.97s/it]

2026-08-21 18:44:56 | INFO    | [CartoCiudad] ✔ Burgos → cod_ine=09059, prov=Burgos, lat=42.3448, lon=-3.6812

Geocodificando Provincias:  17%|█▋        | 9/52 [00:17<01:25,  1.98s/it]

2026-08-21 18:44:58 | INFO    | [CartoCiudad] ✔ Cáceres → cod_ine=10037, prov=Cáceres, lat=39.4745, lon=-6.3717

Geocodificando Provincias:  19%|█▉        | 10/52 [00:19<01:23,  1.99s/it]

2026-08-21 18:45:00 | INFO    | [CartoCiudad] ✔ Cádiz → cod_ine=11012, prov=Cádiz, lat=36.5297, lon=-6.2929

Geocodificando Provincias:  21%|██        | 11/52 [00:21<01:21,  1.99s/it]

2026-08-21 18:45:02 | INFO    | [CartoCiudad] ✔ Castellón de la Plana → cod_ine=12040, prov=Castelló/Castellón, lat=39.9860, lon=-0.0377

Geocodificando Provincias:  23%|██▎       | 12/52 [00:23<01:19,  1.99s/it]

2026-08-21 18:45:04 | INFO    | [CartoCiudad] ✔ Ciudad Real → cod_ine=13034, prov=Ciudad Real, lat=38.9597, lon=-3.8829

Geocodificando Provincias:  25%|██▌       | 13/52 [00:25<01:17,  2.00s/it]

2026-08-21 18:45:06 | INFO    | [CartoCiudad] ✔ Córdoba → cod_ine=14021, prov=Córdoba, lat=37.8846, lon=-4.7760

Geocodificando Provincias:  27%|██▋       | 14/52 [00:27<01:15,  2.00s/it]

2026-08-21 18:45:08 | INFO    | [CartoCiudad] ✔ A Coruña → cod_ine=15030, prov=A Coruña, lat=43.3466, lon=-8.4127

Geocodificando Provincias:  29%|██▉       | 15/52 [00:29<01:13,  2.00s/it]

2026-08-21 18:45:10 | INFO    | [CartoCiudad] ✔ Cuenca → cod_ine=16078, prov=Cuenca, lat=40.0661, lon=-2.1314

Geocodificando Provincias:  31%|███       | 16/52 [00:31<01:12,  2.00s/it]

2026-08-21 18:45:12 | INFO    | [CartoCiudad] ✔ Girona → cod_ine=17079, prov=Girona, lat=41.9793, lon=2.8199

Geocodificando Provincias:  33%|███▎      | 17/52 [00:33<01:09,  2.00s/it]

2026-08-21 18:45:14 | INFO    | [CartoCiudad] ✔ Granada → cod_ine=18087, prov=Granada, lat=37.1735, lon=-3.5995

Geocodificando Provincias:  35%|███▍      | 18/52 [00:35<01:08,  2.00s/it]

2026-08-21 18:45:16 | INFO    | [CartoCiudad] ✔ Guadalajara → cod_ine=19130, prov=Guadalajara, lat=40.7400, lon=-2.5059

Geocodificando Provincias:  37%|███▋      | 19/52 [00:37<01:06,  2.00s/it]

2026-08-21 18:45:18 | INFO    | [CartoCiudad] ✔ Donostia/San Sebastián → cod_ine=20069, prov=Gipuzkoa, lat=43.3224, lon=-1.9839

Geocodificando Provincias:  38%|███▊      | 20/52 [00:39<01:04,  2.00s/it]

2026-08-21 18:45:20 | INFO    | [CartoCiudad] ✔ Huelva → cod_ine=21041, prov=Huelva, lat=37.2576, lon=-6.9485

Geocodificando Provincias:  40%|████      | 21/52 [00:41<01:02,  2.00s/it]

2026-08-21 18:45:22 | INFO    | [CartoCiudad] ✔ Huesca → cod_ine=22125, prov=Huesca, lat=42.1361, lon=-0.0298

Geocodificando Provincias:  42%|████▏     | 22/52 [00:43<01:00,  2.00s/it]

2026-08-21 18:45:24 | INFO    | [CartoCiudad] ✔ Jaén → cod_ine=23050, prov=Jaén, lat=37.7729, lon=-3.7883

Geocodificando Provincias:  44%|████▍     | 23/52 [00:45<00:58,  2.00s/it]

2026-08-21 18:45:26 | INFO    | [CartoCiudad] ✔ León → cod_ine=24089, prov=León, lat=42.6341, lon=-5.9714

Geocodificando Provincias:  46%|████▌     | 24/52 [00:47<00:56,  2.00s/it]

2026-08-21 18:45:28 | INFO    | [CartoCiudad] ✔ Lleida → cod_ine=25120, prov=Lleida, lat=41.6148, lon=0.6268

Geocodificando Provincias:  48%|████▊     | 25/52 [00:49<00:54,  2.00s/it]

2026-08-21 18:45:30 | INFO    | [CartoCiudad] ✔ Logroño → cod_ine=26089, prov=La Rioja, lat=42.4661, lon=-2.4397

Geocodificando Provincias:  50%|█████     | 26/52 [00:51<00:52,  2.00s/it]

2026-08-21 18:45:32 | INFO    | [CartoCiudad] ✔ Lugo → cod_ine=27028, prov=Lugo, lat=43.0395, lon=-7.4568

Geocodificando Provincias:  52%|█████▏    | 27/52 [00:53<00:50,  2.00s/it]

2026-08-21 18:45:34 | INFO    | [CartoCiudad] ✔ Madrid → cod_ine=28079, prov=Madrid, lat=40.4168, lon=-3.7035

Geocodificando Provincias:  54%|█████▍    | 28/52 [00:55<00:48,  2.00s/it]

2026-08-21 18:45:36 | INFO    | [CartoCiudad] ✔ Málaga → cod_ine=29067, prov=Málaga, lat=36.7648, lon=-4.4422

Geocodificando Provincias:  56%|█████▌    | 29/52 [00:57<00:46,  2.00s/it]

2026-08-21 18:45:38 | INFO    | [CartoCiudad] ✔ Murcia → cod_ine=30030, prov=Murcia, lat=37.9348, lon=-1.1131

Geocodificando Provincias:  58%|█████▊    | 30/52 [00:59<00:44,  2.00s/it]

2026-08-21 18:45:40 | INFO    | [CartoCiudad] ✔ Pamplona/Iruña → cod_ine=31201, prov=Navarra, lat=42.8157, lon=-1.6522

Geocodificando Provincias:  60%|█████▉    | 31/52 [01:01<00:42,  2.00s/it]

2026-08-21 18:45:42 | INFO    | [CartoCiudad] ✔ Ourense → cod_ine=32054, prov=Ourense, lat=42.1940, lon=-7.5371

Geocodificando Provincias:  62%|██████▏   | 32/52 [01:03<00:40,  2.01s/it]

2026-08-21 18:45:44 | INFO    | [CartoCiudad] ✔ Oviedo → cod_ine=33044, prov=Asturias, lat=43.3533, lon=-5.8795

Geocodificando Provincias:  63%|██████▎   | 33/52 [01:05<00:37,  2.00s/it]

2026-08-21 18:45:46 | INFO    | [CartoCiudad] ✔ Palencia → cod_ine=34120, prov=Palencia, lat=42.4096, lon=-4.6161

Geocodificando Provincias:  65%|██████▌   | 34/52 [01:07<00:35,  2.00s/it]

2026-08-21 18:45:48 | INFO    | [CartoCiudad] ✔ Las Palmas de Gran Canaria → cod_ine=35016, prov=Las Palmas, lat=28.1289, lon=-15.4349

Geocodificando Provincias:  67%|██████▋   | 35/52 [01:09<00:33,  2.00s/it]

2026-08-21 18:45:50 | INFO    | [CartoCiudad] ✔ Pontevedra → cod_ine=36038, prov=Pontevedra, lat=42.4281, lon=-8.6041

Geocodificando Provincias:  69%|██████▉   | 36/52 [01:11<00:32,  2.00s/it]

2026-08-21 18:45:52 | INFO    | [CartoCiudad] ✔ Salamanca → cod_ine=37274, prov=Salamanca, lat=40.9652, lon=-5.6640

Geocodificando Provincias:  71%|███████   | 37/52 [01:13<00:30,  2.00s/it]

2026-08-21 18:45:54 | INFO    | [CartoCiudad] ✔ Santa Cruz de Tenerife → cod_ine=38038, prov=Santa Cruz de Tenerife, lat=28.4672, lon=-16.2508

Geocodificando Provincias:  73%|███████▎  | 38/52 [01:15<00:28,  2.00s/it]

2026-08-21 18:45:56 | INFO    | [CartoCiudad] ✔ Santander → cod_ine=39075, prov=Cantabria, lat=43.4619, lon=-3.8100

Geocodificando Provincias:  75%|███████▌  | 39/52 [01:17<00:26,  2.00s/it]

2026-08-21 18:45:58 | INFO    | [CartoCiudad] ✔ Segovia → cod_ine=40194, prov=Segovia, lat=40.9481, lon=-4.1172

Geocodificando Provincias:  77%|███████▋  | 40/52 [01:19<00:24,  2.00s/it]

2026-08-21 18:46:00 | INFO    | [CartoCiudad] ✔ Sevilla → cod_ine=41091, prov=Sevilla, lat=37.3886, lon=-5.9953

Geocodificando Provincias:  79%|███████▉  | 41/52 [01:21<00:22,  2.00s/it]

2026-08-21 18:46:02 | INFO    | [CartoCiudad] ✔ Soria → cod_ine=42173, prov=Soria, lat=41.6013, lon=-2.7219

Geocodificando Provincias:  81%|████████  | 42/52 [01:23<00:20,  2.00s/it]

2026-08-21 18:46:04 | INFO    | [CartoCiudad] ✔ Tarragona → cod_ine=43148, prov=Tarragona, lat=41.1172, lon=1.2546

Geocodificando Provincias:  83%|████████▎ | 43/52 [01:25<00:18,  2.00s/it]

2026-08-21 18:46:06 | INFO    | [CartoCiudad] ✔ Teruel → cod_ine=44216, prov=Teruel, lat=40.6005, lon=-0.9229

Geocodificando Provincias:  85%|████████▍ | 44/52 [01:27<00:16,  2.00s/it]

2026-08-21 18:46:08 | INFO    | [CartoCiudad] ✔ Toledo → cod_ine=45168, prov=Toledo, lat=39.8559, lon=-4.0243

Geocodificando Provincias:  87%|████████▋ | 45/52 [01:29<00:14,  2.00s/it]

2026-08-21 18:46:10 | INFO    | [CartoCiudad] ✔ València → cod_ine=46250, prov=València/Valencia, lat=39.4697, lon=-0.3763

Geocodificando Provincias:  88%|████████▊ | 46/52 [01:31<00:12,  2.00s/it]

2026-08-21 18:46:12 | INFO    | [CartoCiudad] ✔ Valladolid → cod_ine=47186, prov=Valladolid, lat=41.6200, lon=-4.7260

Geocodificando Provincias:  90%|█████████ | 47/52 [01:33<00:10,  2.00s/it]

2026-08-21 18:46:14 | INFO    | [CartoCiudad] ✔ Bilbao → cod_ine=48020, prov=Bizkaia, lat=43.2630, lon=-2.9350

Geocodificando Provincias:  92%|█████████▏| 48/52 [01:35<00:08,  2.00s/it]

2026-08-21 18:46:16 | INFO    | [CartoCiudad] ✔ Zamora → cod_ine=49275, prov=Zamora, lat=41.6858, lon=-5.9423

Geocodificando Provincias:  94%|█████████▍| 49/52 [01:37<00:06,  2.00s/it]

2026-08-21 18:46:18 | INFO    | [CartoCiudad] ✔ Zaragoza → cod_ine=50297, prov=Zaragoza, lat=41.6916, lon=-0.9101

Geocodificando Provincias:  96%|█████████▌| 50/52 [01:39<00:04,  2.01s/it]

2026-08-21 18:46:20 | INFO    | [CartoCiudad] ✔ Ceuta → cod_ine=51001, prov=Ceuta, lat=35.8944, lon=-5.3558

Geocodificando Provincias:  98%|█████████▊| 51/52 [01:41<00:01,  2.00s/it]

2026-08-21 18:46:22 | INFO    | [CartoCiudad] ✔ Melilla → cod_ine=52001, prov=Melilla, lat=35.2919, lon=-2.9409

Geocodificando Provincias: 100%|██████████| 52/52 [01:43<00:00,  1.98s/it]

2026-08-21 18:46:22 | INFO    | [csv_writer] ✔  52 filas guardadas → localidades.csv  [columnas: CartoCiudad.cod_ine, CartoCiudad.nombre_municipio, CartoCiudad.provincia, CartoCiudad.ccaa, CartoCiudad.latitud, CartoCiudad.longitud, _meta.fuente_geocod, _meta.fecha_extraccion, _meta.cod_ine_clave, _meta.nombre_municipio]
2026-08-21 18:46:22 | INFO    |
2026-08-21 18:46:22 | INFO    | =================================================================
2026-08-21 18:46:22 | INFO    |   FASE 6 · Oferta Turística de Capitales (OSM Overpass — POIs)
2026-08-21 18:46:22 | INFO    | =================================================================

POIs OSM:   0%|          | 0/52 [00:00<?, ?it/s]

2026-08-21 18:46:38 | INFO    | [OSM] ✔ Vitoria-Gasteiz → hoteles=31, restaurantes=245, atracciones=11, museos=15 [vía Overpass (maps.mail.ru)]

POIs OSM:   2%|▏         | 1/52 [00:15<13:23, 15.76s/it]

2026-08-21 18:46:50 | INFO    | [OSM] ✔ Albacete → hoteles=11, restaurantes=132, atracciones=2, museos=6 [vía Overpass (maps.mail.ru)]

POIs OSM:   4%|▍         | 2/52 [00:27<11:08, 13.37s/it]

2026-08-21 18:47:01 | INFO    | [OSM] ✔ Alicante → hoteles=55, restaurantes=523, atracciones=14, museos=13 [vía Overpass (maps.mail.ru)]

POIs OSM:   6%|▌         | 3/52 [00:39<10:18, 12.63s/it]

2026-08-21 18:47:14 | INFO    | [OSM] ✔ Almería → hoteles=5, restaurantes=16, atracciones=1, museos=0 [vía Overpass (maps.mail.ru)]

POIs OSM:   8%|▊         | 4/52 [00:51<10:05, 12.61s/it]

2026-08-21 18:47:28 | INFO    | [OSM] ↪ Overpass no disponible para 'Ávila'; usando fallback Nominatim...
2026-08-21 18:47:33 | INFO    | [OSM] ✔ Ávila (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=8, museos=20

POIs OSM:  10%|▉         | 5/52 [01:10<11:43, 14.97s/it]

2026-08-21 18:47:48 | INFO    | [OSM] ↪ Overpass no disponible para 'Badajoz'; usando fallback Nominatim...
2026-08-21 18:47:53 | INFO    | [OSM] ✔ Badajoz (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=31

POIs OSM:  12%|█▏        | 6/52 [01:30<12:43, 16.59s/it]

2026-08-21 18:48:04 | INFO    | [OSM] ↪ Overpass no disponible para 'Palma'; usando fallback Nominatim...
2026-08-21 18:48:11 | INFO    | [OSM] ✔ Palma (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=50

POIs OSM:  13%|█▎        | 7/52 [01:48<12:44, 16.98s/it]

2026-08-21 18:48:26 | INFO    | [OSM] ↪ Overpass no disponible para 'Barcelona'; usando fallback Nominatim...
2026-08-21 18:48:27 | INFO    | [OSM] ✔ Barcelona (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=50

POIs OSM:  15%|█▌        | 8/52 [02:05<12:26, 16.96s/it]

2026-08-21 18:48:42 | INFO    | [OSM] ↪ Overpass no disponible para 'Burgos'; usando fallback Nominatim...
2026-08-21 18:48:44 | INFO    | [OSM] ✔ Burgos (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=44, museos=50

POIs OSM:  17%|█▋        | 9/52 [02:21<12:02, 16.81s/it]

2026-08-21 18:49:00 | INFO    | [OSM] ↪ Overpass no disponible para 'Cáceres'; usando fallback Nominatim...
2026-08-21 18:49:02 | INFO    | [OSM] ✔ Cáceres (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=50

POIs OSM:  19%|█▉        | 10/52 [02:39<11:57, 17.09s/it]

2026-08-21 18:49:17 | INFO    | [OSM] ↪ Overpass no disponible para 'Cádiz'; usando fallback Nominatim...
2026-08-21 18:49:19 | INFO    | [OSM] ✔ Cádiz (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=50

POIs OSM:  21%|██        | 11/52 [02:56<11:41, 17.12s/it]

2026-08-21 18:49:33 | INFO    | [OSM] ↪ Overpass no disponible para 'Castellón de la Plana'; usando fallback Nominatim...
2026-08-21 18:49:34 | INFO    | [OSM] ✔ Castellón de la Plana (Fallback Nominatim) → hoteles=14, restaurantes=50, atracciones=0, museos=6

POIs OSM:  23%|██▎       | 12/52 [03:12<11:05, 16.63s/it]

2026-08-21 18:49:49 | INFO    | [OSM] ↪ Overpass no disponible para 'Ciudad Real'; usando fallback Nominatim...
2026-08-21 18:49:51 | INFO    | [OSM] ✔ Ciudad Real (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=22

POIs OSM:  25%|██▌       | 13/52 [03:28<10:47, 16.61s/it]

2026-08-21 18:50:04 | INFO    | [OSM] ✔ Córdoba → hoteles=70, restaurantes=356, atracciones=52, museos=18 [vía Overpass (maps.mail.ru)]

POIs OSM:  27%|██▋       | 14/52 [03:41<09:50, 15.53s/it]

2026-08-21 18:50:16 | INFO    | [OSM] ✔ A Coruña → hoteles=52, restaurantes=496, atracciones=20, museos=25 [vía Overpass (maps.mail.ru)]

POIs OSM:  29%|██▉       | 15/52 [03:54<09:00, 14.62s/it]

2026-08-21 18:50:29 | INFO    | [OSM] ✔ Cuenca → hoteles=29, restaurantes=75, atracciones=16, museos=10 [vía Overpass (maps.mail.ru)]

POIs OSM:  31%|███       | 16/52 [04:06<08:24, 14.02s/it]

2026-08-21 18:50:45 | INFO    | [OSM] ✔ Girona → hoteles=37, restaurantes=329, atracciones=8, museos=11 [vía Overpass (maps.mail.ru)]

POIs OSM:  33%|███▎      | 17/52 [04:22<08:25, 14.45s/it]

2026-08-21 18:50:57 | INFO    | [OSM] ✔ Granada → hoteles=135, restaurantes=573, atracciones=57, museos=27 [vía Overpass (maps.mail.ru)]

POIs OSM:  35%|███▍      | 18/52 [04:34<07:47, 13.75s/it]

2026-08-21 18:51:11 | INFO    | [OSM] ↪ Overpass no disponible para 'Guadalajara'; usando fallback Nominatim...
2026-08-21 18:51:13 | INFO    | [OSM] ✔ Guadalajara (Fallback Nominatim) → hoteles=50, restaurantes=47, atracciones=0, museos=47

POIs OSM:  37%|███▋      | 19/52 [04:51<08:01, 14.60s/it]

2026-08-21 18:51:28 | INFO    | [OSM] ↪ Overpass no disponible para 'Donostia/San Sebastián'; usando fallback Nominatim...
2026-08-21 18:51:30 | INFO    | [OSM] ✔ Donostia/San Sebastián (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=11

POIs OSM:  38%|███▊      | 20/52 [05:07<08:05, 15.18s/it]

2026-08-21 18:51:46 | INFO    | [OSM] ↪ Overpass no disponible para 'Huelva'; usando fallback Nominatim...
2026-08-21 18:51:48 | INFO    | [OSM] ✔ Huelva (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=28

POIs OSM:  40%|████      | 21/52 [05:25<08:18, 16.07s/it]

2026-08-21 18:52:03 | INFO    | [OSM] ↪ Overpass no disponible para 'Huesca'; usando fallback Nominatim...
2026-08-21 18:52:05 | INFO    | [OSM] ✔ Huesca (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=34

POIs OSM:  42%|████▏     | 22/52 [05:42<08:06, 16.23s/it]

2026-08-21 18:52:19 | INFO    | [OSM] ↪ Overpass no disponible para 'Jaén'; usando fallback Nominatim...
2026-08-21 18:52:21 | INFO    | [OSM] ✔ Jaén (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=50

POIs OSM:  44%|████▍     | 23/52 [05:58<07:53, 16.33s/it]

2026-08-21 18:52:36 | INFO    | [OSM] ↪ Overpass no disponible para 'León'; usando fallback Nominatim...
2026-08-21 18:52:38 | INFO    | [OSM] ✔ León (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=50, museos=45

POIs OSM:  46%|████▌     | 24/52 [06:15<07:38, 16.38s/it]

2026-08-21 18:52:54 | INFO    | [OSM] ↪ Overpass no disponible para 'Lleida'; usando fallback Nominatim...
2026-08-21 18:52:56 | INFO    | [OSM] ✔ Lleida (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=48

POIs OSM:  48%|████▊     | 25/52 [06:33<07:37, 16.95s/it]

2026-08-21 18:53:11 | INFO    | [OSM] ↪ Overpass no disponible para 'Logroño'; usando fallback Nominatim...
2026-08-21 18:53:12 | INFO    | [OSM] ✔ Logroño (Fallback Nominatim) → hoteles=33, restaurantes=50, atracciones=0, museos=8

POIs OSM:  50%|█████     | 26/52 [06:50<07:17, 16.84s/it]

2026-08-21 18:53:25 | INFO    | [OSM] ↪ Overpass no disponible para 'Lugo'; usando fallback Nominatim...
2026-08-21 18:53:26 | INFO    | [OSM] ✔ Lugo (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=44

POIs OSM:  52%|█████▏    | 27/52 [07:04<06:39, 15.99s/it]

2026-08-21 18:53:41 | INFO    | [OSM] ↪ Overpass no disponible para 'Madrid'; usando fallback Nominatim...
2026-08-21 18:53:43 | INFO    | [OSM] ✔ Madrid (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=1, museos=50

POIs OSM:  54%|█████▍    | 28/52 [07:20<06:27, 16.15s/it]

2026-08-21 18:53:58 | INFO    | [OSM] ↪ Overpass no disponible para 'Málaga'; usando fallback Nominatim...
2026-08-21 18:54:00 | INFO    | [OSM] ✔ Málaga (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=1, museos=50

POIs OSM:  56%|█████▌    | 29/52 [07:37<06:14, 16.28s/it]

2026-08-21 18:54:14 | INFO    | [OSM] ↪ Overpass no disponible para 'Murcia'; usando fallback Nominatim...
2026-08-21 18:54:16 | INFO    | [OSM] ✔ Murcia (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=50

POIs OSM:  58%|█████▊    | 30/52 [07:53<05:58, 16.29s/it]

2026-08-21 18:54:27 | INFO    | [OSM] ✔ Pamplona/Iruña → hoteles=47, restaurantes=272, atracciones=17, museos=10 [vía Overpass (maps.mail.ru)]

POIs OSM:  60%|█████▉    | 31/52 [08:05<05:11, 14.85s/it]

2026-08-21 18:54:39 | INFO    | [OSM] ✔ Ourense → hoteles=0, restaurantes=2, atracciones=1, museos=0 [vía Overpass (maps.mail.ru)]

POIs OSM:  62%|██████▏   | 32/52 [08:16<04:37, 13.89s/it]

2026-08-21 18:54:54 | INFO    | [OSM] ↪ Overpass no disponible para 'Oviedo'; usando fallback Nominatim...
2026-08-21 18:54:56 | INFO    | [OSM] ✔ Oviedo (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=12

POIs OSM:  63%|██████▎   | 33/52 [08:33<04:39, 14.71s/it]

2026-08-21 18:55:10 | INFO    | [OSM] ↪ Overpass no disponible para 'Palencia'; usando fallback Nominatim...
2026-08-21 18:55:15 | INFO    | [OSM] ✔ Palencia (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=4, museos=50

POIs OSM:  65%|██████▌   | 34/52 [08:52<04:47, 15.97s/it]

2026-08-21 18:55:32 | INFO    | [OSM] ↪ Overpass no disponible para 'Las Palmas de Gran Canaria'; usando fallback Nominatim...
2026-08-21 18:55:34 | INFO    | [OSM] ✔ Las Palmas de Gran Canaria (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=12

POIs OSM:  67%|██████▋   | 35/52 [09:11<04:49, 17.03s/it]

2026-08-21 18:55:42 | INFO    | [OSM] ↪ Overpass no disponible para 'Pontevedra'; usando fallback Nominatim...
2026-08-21 18:55:48 | INFO    | [OSM] ✔ Pontevedra (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=50

POIs OSM:  69%|██████▉   | 36/52 [09:26<04:19, 16.24s/it]

2026-08-21 18:56:00 | INFO    | [OSM] ↪ Overpass no disponible para 'Salamanca'; usando fallback Nominatim...
2026-08-21 18:56:02 | INFO    | [OSM] ✔ Salamanca (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=26, museos=50

POIs OSM:  71%|███████   | 37/52 [09:39<03:50, 15.39s/it]

2026-08-21 18:56:17 | INFO    | [OSM] ↪ Overpass no disponible para 'Santa Cruz de Tenerife'; usando fallback Nominatim...
2026-08-21 18:56:22 | INFO    | [OSM] ✔ Santa Cruz de Tenerife (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=50

POIs OSM:  73%|███████▎  | 38/52 [09:59<03:55, 16.82s/it]

2026-08-21 18:56:35 | INFO    | [OSM] ✔ Santander → hoteles=69, restaurantes=315, atracciones=13, museos=25 [vía Overpass (maps.mail.ru)]

POIs OSM:  75%|███████▌  | 39/52 [10:12<03:23, 15.63s/it]

2026-08-21 18:56:50 | INFO    | [OSM] ↪ Overpass no disponible para 'Segovia'; usando fallback Nominatim...
2026-08-21 18:56:55 | INFO    | [OSM] ✔ Segovia (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=10, museos=50

POIs OSM:  77%|███████▋  | 40/52 [10:33<03:24, 17.06s/it]

2026-08-21 18:57:10 | INFO    | [OSM] ↪ Overpass no disponible para 'Sevilla'; usando fallback Nominatim...
2026-08-21 18:57:15 | INFO    | [OSM] ✔ Sevilla (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=50

POIs OSM:  79%|███████▉  | 41/52 [10:52<03:15, 17.77s/it]

2026-08-21 18:57:29 | INFO    | [OSM] ↪ Overpass no disponible para 'Soria'; usando fallback Nominatim...
2026-08-21 18:57:30 | INFO    | [OSM] ✔ Soria (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=8, museos=50

POIs OSM:  81%|████████  | 42/52 [11:08<02:51, 17.15s/it]

2026-08-21 18:57:45 | INFO    | [OSM] ↪ Overpass no disponible para 'Tarragona'; usando fallback Nominatim...
2026-08-21 18:57:46 | INFO    | [OSM] ✔ Tarragona (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=50

POIs OSM:  83%|████████▎ | 43/52 [11:24<02:31, 16.81s/it]

2026-08-21 18:57:55 | INFO    | [OSM] ✔ Teruel → hoteles=2, restaurantes=4, atracciones=3, museos=2 [vía Overpass (maps.mail.ru)]

POIs OSM:  85%|████████▍ | 44/52 [11:33<01:55, 14.50s/it]

2026-08-21 18:58:10 | INFO    | [OSM] ↪ Overpass no disponible para 'Toledo'; usando fallback Nominatim...
2026-08-21 18:58:12 | INFO    | [OSM] ✔ Toledo (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=50

POIs OSM:  87%|████████▋ | 45/52 [11:50<01:46, 15.18s/it]

2026-08-21 18:58:27 | INFO    | [OSM] ↪ Overpass no disponible para 'València'; usando fallback Nominatim...
2026-08-21 18:58:29 | INFO    | [OSM] ✔ València (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=2, museos=50

POIs OSM:  88%|████████▊ | 46/52 [12:06<01:33, 15.61s/it]

2026-08-21 18:58:44 | INFO    | [OSM] ↪ Overpass no disponible para 'Valladolid'; usando fallback Nominatim...
2026-08-21 18:58:45 | INFO    | [OSM] ✔ Valladolid (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=20, museos=46

POIs OSM:  90%|█████████ | 47/52 [12:23<01:19, 15.90s/it]

2026-08-21 18:59:00 | INFO    | [OSM] ↪ Overpass no disponible para 'Bilbao'; usando fallback Nominatim...
2026-08-21 18:59:02 | INFO    | [OSM] ✔ Bilbao (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=1, museos=50

POIs OSM:  92%|█████████▏| 48/52 [12:39<01:04, 16.07s/it]

2026-08-21 18:59:18 | INFO    | [OSM] ↪ Overpass no disponible para 'Zamora'; usando fallback Nominatim...
2026-08-21 18:59:20 | INFO    | [OSM] ✔ Zamora (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=13, museos=41

POIs OSM:  94%|█████████▍| 49/52 [12:57<00:50, 16.67s/it]

2026-08-21 18:59:33 | INFO    | [OSM] ✔ Zaragoza → hoteles=60, restaurantes=833, atracciones=10, museos=52 [vía Overpass (maps.mail.ru)]

POIs OSM:  96%|█████████▌| 50/52 [13:10<00:31, 15.56s/it]

2026-08-21 18:59:47 | INFO    | [OSM] ✔ Ceuta → hoteles=8, restaurantes=43, atracciones=3, museos=5 [vía Overpass (maps.mail.ru)]

POIs OSM:  98%|█████████▊| 51/52 [13:25<00:15, 15.22s/it]

2026-08-21 19:00:04 | INFO    | [OSM] ↪ Overpass no disponible para 'Melilla'; usando fallback Nominatim...
2026-08-21 19:00:05 | INFO    | [OSM] ✔ Melilla (Fallback Nominatim) → hoteles=8, restaurantes=25, atracciones=0, museos=11

POIs OSM: 100%|██████████| 52/52 [13:43<00:00, 15.83s/it]

2026-08-21 19:00:05 | INFO    | [csv_writer] ✔  52 filas guardadas → oferta_osm.csv  [columnas: OSM_Overpass.num_hoteles, OSM_Overpass.num_restaurantes, OSM_Overpass.num_atracciones, OSM_Overpass.num_museos, OSM_Overpass.fuente, OSM_Overpass.fecha_extraccion, _meta.cod_ine_clave, _meta.nombre_municipio]
2026-08-21 19:00:05 | INFO    |
2026-08-21 19:00:05 | INFO    | =================================================================
2026-08-21 19:00:05 | INFO    |   FASE 7 · POIs TripAdvisor (requiere API key)
2026-08-21 19:00:05 | INFO    | =================================================================
2026-08-21 19:00:05 | WARNING | [TripAdvisor] ⊘ TRIPADVISOR_API_KEY no configurada. Define la clave en .env para activar este extractor.
2026-08-21 19:00:05 | WARNING | [reporter] ⊘  TripAdvisor omitido → TRIPADVISOR_API_KEY no configurada en .env. Solicita la clave en tripadvisor.com/developers.
2026-08-21 19:00:05 | INFO    |
2026-08-21 19:00:05 | INFO    | =================================================================
2026-08-21 19:00:05 | INFO    |   FASE 8 · Catálogo Nacional de Datasets Abiertos (datos.gob.es)
2026-08-21 19:00:05 | INFO    | =================================================================
2026-08-21 19:00:05 | INFO    | [DatosGob] ▶ Buscando datasets relacionados con 'turismo' en el catálogo nacional...

2026-08-21 19:00:06 | INFO    | [DatosGob] ✔ 'turismo' → 0 recursos encontrados en el catálogo.
2026-08-21 19:00:06 | WARNING | [reporter] ✗  DatosGob | turismo → Error: Búsqueda 'turismo' en datos.gob.es devolvió DataFrame vacío o error.
2026-08-21 19:00:06 | INFO    | [DatosGob] ▶ Buscando datasets relacionados con 'ocupación hotelera' en el catálogo nacional...
2026-08-21 19:00:07 | INFO    | [DatosGob] ✔ 'ocupación hotelera' → 0 recursos encontrados en el catálogo.
2026-08-21 19:00:07 | WARNING | [reporter] ✗  DatosGob | ocupación hotelera → Error: Búsqueda 'ocupación hotelera' en datos.gob.es devolvió DataFrame vacío o error.
2026-08-21 19:00:07 | INFO    | [DatosGob] ▶ Buscando datasets relacionados con 'turismo rural' en el catálogo nacional...
2026-08-21 19:00:07 | INFO    | [DatosGob] ✔ 'turismo rural' → 0 recursos encontrados en el catálogo.
2026-08-21 19:00:07 | WARNING | [reporter] ✗  DatosGob | turismo rural → Error: Búsqueda 'turismo rural' en datos.gob.es devolvió DataFrame vacío o error.
2026-08-21 19:00:07 | INFO    | [DatosGob] ▶ Buscando datasets relacionados con 'alojamientos turísticos' en el catálogo nacional...
2026-08-21 19:00:08 | INFO    | [DatosGob] ✔ 'alojamientos turísticos' → 0 recursos encontrados en el catálogo.
2026-08-21 19:00:08 | WARNING | [reporter] ✗  DatosGob | alojamientos turísticos → Error: Búsqueda 'alojamientos turísticos' en datos.gob.es devolvió DataFrame vacío o error.
2026-08-21 19:00:08 | INFO    |
2026-08-21 19:00:08 | INFO    | =================================================================
2026-08-21 19:00:08 | INFO    |   FASE 9 · Cierre del pipeline y Generación de Reporte
2026-08-21 19:00:08 | INFO    | =================================================================
2026-08-21 19:00:08 | WARNING | [reporter] ⚠  Reporte de fallos guardado (5 entradas) → reporte_fallos.csv

============================================================
  RESUMEN DE FALLOS DEL PIPELINE
============================================================
  [TripAdvisor] — — Omitido: TRIPADVISOR_API_KEY no configurada en .env. Solicita la clave en tripadvisor.com/developers.
  [DatosGob] turismo — Error: Búsqueda 'turismo' en datos.gob.es devolvió DataFrame vacío o error.
  [DatosGob] ocupación hotelera — Error: Búsqueda 'ocupación hotelera' en datos.gob.es devolvió DataFrame vacío o error.
  [DatosGob] turismo rural — Error: Búsqueda 'turismo rural' en datos.gob.es devolvió DataFrame vacío o error.
  [DatosGob] alojamientos turísticos — Error: Búsqueda 'alojamientos turísticos' en datos.gob.es devolvió DataFrame vacío o error.
============================================================
  Total fallos: 5
============================================================

2026-08-21 19:00:08 | INFO    | Pipeline nacional completado.
2026-08-21 19:00:08 | INFO    | Archivos CSV generados en: C:\Users\Manuel Santos\Escritorio\MASTER\TFM - TUI\Antigravity-Prueba\data\processed
2026-08-21 19:00:08 | INFO    | Log de sesión guardado en: C:\Users\Manuel Santos\Escritorio\MASTER\TFM - TUI\Antigravity-Prueba\data\logs\log_sesion_20260821_184429.txt

In [ ]:
localidades = pd.read_csv('data/processed/flujo_ine_localidad.csv', sep=',', encoding='UTF-8')
provincias = pd.read_csv('data/processed/flujo_ine_provincia.csv', sep=',', encoding='UTF-8')
localidades_data = pd.read_csv('data/processed/localidades.csv', sep=',', encoding='UTF-8')
OpenStreetDf = pd.read_csv('data/processed/oferta_osm.csv', sep=',', encoding='UTF-8')
provincias_data = pd.read_csv('data/processed/municipios_espana.csv', sep=',', encoding='UTF-8')
clima_df = pd.read_csv('data/processed/clima_aemet.csv', sep=',', encoding='UTF-8')

In [28]:
localidades.head()

,INE_EOH_MUN.punto_turistico,INE_EOH_MUN.indicador,INE_EOH_MUN.residencia,INE_EOH_MUN.nombre_serie_completo,INE_EOH_MUN.cod_serie,INE_EOH_MUN.anio,INE_EOH_MUN.periodo,INE_EOH_MUN.valor,INE_EOH_MUN.fuente,INE_EOH_MUN.tabla_id,_meta.fecha_extraccion
0,Vitoria-Gastéiz,viajeros,Residentes en España,Nacional. Viajeros. Vitoria-Gastéiz. Residente...,EOT2611,2026,NaN,18734.0,INE_EOH_MUN,2078,2026-08-21T16:44:39.429873
1,Vitoria-Gastéiz,viajeros,Residentes en España,Nacional. Viajeros. Vitoria-Gastéiz. Residente...,EOT2611,2026,NaN,19464.0,INE_EOH_MUN,2078,2026-08-21T16:44:39.429873
2,Vitoria-Gastéiz,viajeros,Residentes en España,Nacional. Viajeros. Vitoria-Gastéiz. Residente...,EOT2611,2026,NaN,20574.0,INE_EOH_MUN,2078,2026-08-21T16:44:39.429873
3,Vitoria-Gastéiz,viajeros,Residentes en España,Nacional. Viajeros. Vitoria-Gastéiz. Residente...,EOT2611,2026,NaN,21012.0,INE_EOH_MUN,2078,2026-08-21T16:44:39.429873
4,Vitoria-Gastéiz,viajeros,Residentes en España,Nacional. Viajeros. Vitoria-Gastéiz. Residente...,EOT2611,2026,NaN,20189.0,INE_EOH_MUN,2078,2026-08-21T16:44:39.429873

In [29]:
localidades_data.head()

,CartoCiudad.cod_ine,CartoCiudad.nombre_municipio,CartoCiudad.provincia,CartoCiudad.ccaa,CartoCiudad.latitud,CartoCiudad.longitud,_meta.fuente_geocod,_meta.fecha_extraccion,_meta.cod_ine_clave,_meta.nombre_municipio
0,1059,Vitoria-Gasteiz,Araba/Álava,País Vasco/Euskadi,42.850584,-2.661450,CartoCiudad+IGN,2026-08-21T16:44:40.737543,1059,Vitoria-Gasteiz
1,2003,Albacete,Albacete,Castilla-La Mancha,38.995092,-1.855915,CartoCiudad+IGN,2026-08-21T16:44:42.509846,2003,Albacete
2,3014,Alacant/Alicante,Alacant/Alicante,Comunitat Valenciana,38.343637,-0.488171,CartoCiudad+IGN,2026-08-21T16:44:44.511789,3014,Alicante
3,4013,Almería,Almería,Andalucía,36.868574,-2.312028,CartoCiudad+IGN,2026-08-21T16:44:46.512755,4013,Almería
4,5019,Ávila,Ávila,Castilla y León,40.657195,-4.662668,CartoCiudad+IGN,2026-08-21T16:44:48.513431,5019,Ávila

In [30]:
provincias[provincias['INE_EOH_PROV.indicador']=='Viajero'].head()

,INE_EOH_PROV.ambito,INE_EOH_PROV.indicador,INE_EOH_PROV.residencia,INE_EOH_PROV.nombre_serie_completo,INE_EOH_PROV.cod_serie,INE_EOH_PROV.anio,INE_EOH_PROV.periodo,INE_EOH_PROV.valor,INE_EOH_PROV.fuente,INE_EOH_PROV.tabla_id,_meta.fecha_extraccion
1080,Asturias,Viajero,Total categorías,Asturias. Viajero. Total categorías. Total. Da...,EOT22203,2026,NaN,251471.0,INE_EOH_PROV,2074,2026-08-21T16:44:35.799224
1081,Asturias,Viajero,Total categorías,Asturias. Viajero. Total categorías. Total. Da...,EOT22203,2026,NaN,206637.0,INE_EOH_PROV,2074,2026-08-21T16:44:35.799224
1082,Asturias,Viajero,Total categorías,Asturias. Viajero. Total categorías. Total. Da...,EOT22203,2026,NaN,175443.0,INE_EOH_PROV,2074,2026-08-21T16:44:35.799224
1083,Asturias,Viajero,Total categorías,Asturias. Viajero. Total categorías. Total. Da...,EOT22203,2026,NaN,147543.0,INE_EOH_PROV,2074,2026-08-21T16:44:35.799224
1084,Asturias,Viajero,Total categorías,Asturias. Viajero. Total categorías. Total. Da...,EOT22203,2026,NaN,113361.0,INE_EOH_PROV,2074,2026-08-21T16:44:35.799224

In [31]:
provincias_data.head()

,INE_Pob_MUN.nombre_municipio,INE_Pob_MUN.poblacion_oficial,INE_Pob_MUN.anio,INE_Pob_MUN.cod_serie,INE_Pob_MUN.nombre_serie_completo,INE_Pob_MUN.fuente,_meta.fecha_extraccion
0,Ababuj,73.0,2025,DPOP19723,Ababuj. Total. Total habitantes. Personas.,INE_Padron_Tabla_29005,2026-08-21T16:44:32.114449
1,Abades,849.0,2025,DPOP17671,Abades. Total. Total habitantes. Personas.,INE_Padron_Tabla_29005,2026-08-21T16:44:32.114449
2,Abadía,337.0,2025,DPOP4663,Abadía. Total. Total habitantes. Personas.,INE_Padron_Tabla_29005,2026-08-21T16:44:32.114449
3,Abadín,2239.0,2025,DPOP12721,Abadín. Total. Total habitantes. Personas.,INE_Padron_Tabla_29005,2026-08-21T16:44:32.114449
4,Abadiño,7768.0,2025,DPOP22525,Abadiño. Total. Total habitantes. Personas.,INE_Padron_Tabla_29005,2026-08-21T16:44:32.114449

In [32]:
OpenStreetDf.head()

,OSM_Overpass.num_hoteles,OSM_Overpass.num_restaurantes,OSM_Overpass.num_atracciones,OSM_Overpass.num_museos,OSM_Overpass.fuente,OSM_Overpass.fecha_extraccion,_meta.cod_ine_clave,_meta.nombre_municipio
0,31,245,11,15,Overpass (maps.mail.ru),2026-08-21T16:46:38.340713,1059,Vitoria-Gasteiz
1,11,132,2,6,Overpass (maps.mail.ru),2026-08-21T16:46:50.028919,2003,Albacete
2,55,523,14,13,Overpass (maps.mail.ru),2026-08-21T16:47:01.772695,3014,Alicante
3,5,16,1,0,Overpass (maps.mail.ru),2026-08-21T16:47:14.349759,4013,Almería
4,50,50,8,20,OSM_Nominatim_Fallback,2026-08-21T16:47:33.495891,5019,Ávila