In [2]:
import os
import warnings
warnings.filterwarnings('ignore', category=DeprecationWarning)
import numpy as np
import pandas as pd
import seaborn as sns
from ydata_profiling import ProfileReport

En primer lugar, ejecutamos el main.py de extracción de datos, para actualizar mantener los datos actualizados

In [89]:
actualizar = input("""¿Deseas actualizar los archivos de datos? (s/n)
         Ten en cuenta que puede tardar bastante en hacer las consultas, 
         por lo que si ya has cargado los datos una vez recomiendo no volver a hacerlo: """)

if actualizar=="s":
    %run main.py
elif actualizar=="n":
    print("No se han actualizado los archivos de datos.")

No se han actualizado los archivos de datos.

In [3]:
INE_localidades = pd.read_csv('data/processed/flujo_ine_localidad.csv', sep=',', encoding='UTF-8')
f_INE_provincias = pd.read_csv('data/processed/flujo_ine_provincia.csv', sep=',', encoding='UTF-8')
INE_provincias = pd.read_csv('data/processed/INE_provincias.csv', sep=',', encoding='UTF-8')
provincias_data = pd.read_csv('data/processed/Carto_provincias.csv', sep=',', encoding='UTF-8')
OpenStreetDf = pd.read_csv('data/processed/oferta_osm.csv', sep=',', encoding='UTF-8')
localidades_data = pd.read_csv('data/processed/municipios_espana.csv', sep=',', encoding='UTF-8')
clima_df = pd.read_csv('data/processed/clima_aemet.csv', sep=',', encoding='UTF-8')

In [5]:
#INE_localidades.head()
#INE_localidades.shape --> Resultado: (6610, 11)
INE_localidades.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6610 entries, 0 to 6609
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   COD                     6610 non-null   object
 1   Nombre                  6610 non-null   object
 2   T3_Unidad               6610 non-null   object
 3   T3_Escala               6610 non-null   object
 4   Fecha                   6610 non-null   object
 5   T3_Periodo              6610 non-null   object
 6   T3_TipoDato             6610 non-null   object
 7   Anyo                    6610 non-null   int64
 8   Valor                   5560 non-null   float64
 9   MetaData_json           6610 non-null   object
 10  tabla_id                6610 non-null   int64
 11  _meta.fecha_extraccion  6610 non-null   object
dtypes: float64(1), int64(2), object(9)
memory usage: 619.8+ KB

In [6]:
#localidades_data.head()
#
provincias_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   query                   52 non-null     object
 1   id                      52 non-null     int64
 2   muniCode                52 non-null     int64
 3   provinceCode            52 non-null     int64
 4   muni                    52 non-null     object
 5   province                52 non-null     object
 6   comunidadAutonoma       52 non-null     object
 7   lat                     52 non-null     float64
 8   lng                     52 non-null     float64
 9   type                    52 non-null     object
 10  state                   52 non-null     int64
 11  raw_json                52 non-null     object
 12  _meta.fecha_extraccion  52 non-null     object
dtypes: float64(2), int64(4), object(7)
memory usage: 5.4+ KB

In [7]:

f_INE_provincias.tail()

,COD,Nombre,T3_Unidad,T3_Escala,Fecha,T3_Periodo,T3_TipoDato,Anyo,Valor,MetaData_json,tabla_id,_meta.fecha_extraccion
5035,EOT1822,Melilla. Pernoctaciones. Residentes en el extr...,Pernoctaciones,,2025-12-01T00:00:00.000+01:00,M12,Provisional,2025,1844.0,"[{""Id"": 8995, ""T3_Variable"": ""Comunidades y Ci...",2074,2026-08-24T19:52:29.866208
5036,EOT1822,Melilla. Pernoctaciones. Residentes en el extr...,Pernoctaciones,,2025-11-01T00:00:00.000+01:00,M11,Provisional,2025,1479.0,"[{""Id"": 8995, ""T3_Variable"": ""Comunidades y Ci...",2074,2026-08-24T19:52:29.866208
5037,EOT1822,Melilla. Pernoctaciones. Residentes en el extr...,Pernoctaciones,,2025-10-01T00:00:00.000+02:00,M10,Provisional,2025,2448.0,"[{""Id"": 8995, ""T3_Variable"": ""Comunidades y Ci...",2074,2026-08-24T19:52:29.866208
5038,EOT1822,Melilla. Pernoctaciones. Residentes en el extr...,Pernoctaciones,,2025-09-01T00:00:00.000+02:00,M09,Provisional,2025,2077.0,"[{""Id"": 8995, ""T3_Variable"": ""Comunidades y Ci...",2074,2026-08-24T19:52:29.866208
5039,EOT1822,Melilla. Pernoctaciones. Residentes en el extr...,Pernoctaciones,,2025-08-01T00:00:00.000+02:00,M08,Provisional,2025,4788.0,"[{""Id"": 8995, ""T3_Variable"": ""Comunidades y Ci...",2074,2026-08-24T19:52:29.866208

In [94]:
INE_provincias.head()
#INE_provincias[INE_provincias['INE_EOH_PROV.indicador']=='Viajero'].head()
#INE_provincias.info()

,COD,Nombre,T3_Unidad,T3_Escala,Fecha,T3_Periodo,T3_TipoDato,Anyo,Valor,MetaData_json,tabla_id,_meta.fecha_extraccion
0,DPOP1,Total Nacional. Total. Total habitantes. Perso...,Personas,,2021-01-01T00:00:00.000+01:00,A,Definitivo,2021,47385107.0,"[{""Id"": 16473, ""T3_Variable"": ""Comunidades y C...",2852,2026-08-24T19:52:20.261921
1,DPOP2,Total Nacional. Hombres. Total habitantes. Per...,Personas,,2021-01-01T00:00:00.000+01:00,A,Definitivo,2021,23222953.0,"[{""Id"": 16473, ""T3_Variable"": ""Comunidades y C...",2852,2026-08-24T19:52:20.261921
2,DPOP3,Total Nacional. Mujeres. Total habitantes. Per...,Personas,,2021-01-01T00:00:00.000+01:00,A,Definitivo,2021,24162154.0,"[{""Id"": 16473, ""T3_Variable"": ""Comunidades y C...",2852,2026-08-24T19:52:20.261921
3,DPOP160,Albacete. Total. Total habitantes. Personas.,Personas,,2021-01-01T00:00:00.000+01:00,A,Definitivo,2021,386464.0,"[{""Id"": 3, ""T3_Variable"": ""Provincias"", ""Nombr...",2852,2026-08-24T19:52:20.261921
4,DPOP161,Albacete. Hombres. Total habitantes. Personas.,Personas,,2021-01-01T00:00:00.000+01:00,A,Definitivo,2021,193205.0,"[{""Id"": 3, ""T3_Variable"": ""Provincias"", ""Nombr...",2852,2026-08-24T19:52:20.261921

In [95]:
#provincias_data.head()
provincias_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   query                   52 non-null     str
 1   id                      52 non-null     int64
 2   muniCode                52 non-null     int64
 3   provinceCode            52 non-null     int64
 4   muni                    52 non-null     str
 5   province                52 non-null     str
 6   comunidadAutonoma       52 non-null     str
 7   lat                     52 non-null     float64
 8   lng                     52 non-null     float64
 9   type                    52 non-null     str
 10  state                   52 non-null     int64
 11  raw_json                52 non-null     str
 12  _meta.fecha_extraccion  52 non-null     str
dtypes: float64(2), int64(4), str(7)
memory usage: 5.4 KB

In [96]:
#OpenStreetDf.head()
OpenStreetDf.info()

<class 'pandas.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   query_name              52 non-null     str
 1   lat                     52 non-null     float64
 2   lon                     52 non-null     float64
 3   radio_metros            52 non-null     int64
 4   mirror_usado            52 non-null     str
 5   elements_raw_json       52 non-null     str
 6   _meta.fecha_extraccion  52 non-null     str
dtypes: float64(2), int64(1), str(4)
memory usage: 3.0 KB

Cambios necesarios:
- INE_localidades y localidades_data se deben combinar
- Provincias_data se debe pivotar para tener en varias columnas los valores numéricos y sólo 52 filas
- En f_INE_provincias, INE_Provincias, Provincias_data y OpenStreetDF se deben combinar

El resultado debe ser dos DataFrames, uno para localidades, y otro para provincias. Posteriormente se deberá hacer un Left Join en las localidades para los municipios. Posteriormente, se deben combinar ambos Dfs

Comenzamos filtrando y reduciendo las columnas en localidades_data

In [ ]:
# Primero, dividimos la columna de 'Nombre' usando el metodo .str.split()
columnas = ['Localidad', 'Genero', 'Metrica', 'Unidad']
localidades_data[columnas] = localidades_data['Nombre'].str.split('.', n=3, expand=True)

for col in columnas:
    localidades_data[col] = localidades_data[col].str.strip() #Eliminamos los espacios al inicio y final con un bucle

# Suprimimos las columnas que no vamos a necesitar
localidades_data.drop(columns=['Nombre', 'Fecha', 'T3_Unidad', 'T3_Escala', 'T3_Periodo', 'T3_TipoDato','Anyo', 'tabla_id', 'MetaData_json', '_meta.fecha_extraccion'],
                     inplace=True
                     )

# Como nos interesa la poblacion total por municipio, filtramos Genero == 'Total
localidades_data = localidades_data[localidades_data['Genero'] == 'Total']

# Comprobamos el resultado
localidades_data.head()

          COD   Valor Localidad Genero           Metrica     Unidad
0   DPOP19723    73.0    Ababuj  Total  Total habitantes  Personas.
3   DPOP17671   849.0    Abades  Total  Total habitantes  Personas.
6    DPOP4663   337.0    Abadía  Total  Total habitantes  Personas.
9   DPOP12721  2239.0    Abadín  Total  Total habitantes  Personas.
12  DPOP22525  7768.0   Abadiño  Total  Total habitantes  Personas.