In [9]:
import pandas as pd
import numpy as np
import os

En primer lugar, ejecutamos el main.py de extracción de datos, para actualizar mantener los datos actualizados

In [10]:
actualizar = input("""¿Deseas actualizar los archivos de datos? (s/n)
         Ten en cuenta que puede tardar bastante en hacer las consultas, 
         por lo que si ya has cargado los datos una vez recomiendo no volver a hacerlo: """)

if actualizar=="s":
    %run main.py
elif actualizar=="n":
    print("No se han actualizado los archivos de datos.")

2026-08-20 19:52:42 | INFO    |
2026-08-20 19:52:42 | INFO    | =================================================================
2026-08-20 19:52:42 | INFO    |   FASE 0 · Inicialización del pipeline (Ámbito: España Completa)
2026-08-20 19:52:42 | INFO    | =================================================================
2026-08-20 19:52:42 | INFO    | Log de sesión → C:\Users\Manuel Santos\Escritorio\MASTER\TFM - TUI\Antigravity-Prueba\data\logs\log_sesion_20260820_195242.txt
2026-08-20 19:52:42 | INFO    | Fuentes activas: datosgob, flujo_ine_localidad, flujo_ine_provincia, localidades, municipios_espana, provincias, tripadvisor, turismo_oferta_osm
2026-08-20 19:52:42 | INFO    | Períodos históricos INE a descargar: 12 meses
2026-08-20 19:52:42 | INFO    |
2026-08-20 19:52:42 | INFO    | =================================================================
2026-08-20 19:52:42 | INFO    |   FASE 1 · Maestro de las 52 Provincias y Ciudades Autónomas de España (INE Tabla 2852)
2026-08-20 19:52:42 | INFO    | =================================================================
2026-08-20 19:52:42 | INFO    | [INE_Pob_PROV] ▶ Descargando cifras oficiales de población por provincia (Tabla 2852)...
2026-08-20 19:52:42 | INFO    | [INE] ✔ Tabla 2852 descargada: 159 series.
2026-08-20 19:52:42 | INFO    | [INE_Pob_PROV] ✔ 52 provincias/ciudades autónomas procesadas correctamente.
2026-08-20 19:52:42 | INFO    | [csv_writer] ✔  52 filas guardadas → provincias.csv  [columnas: INE_Pob_PROV.provincia, INE_Pob_PROV.poblacion_total, INE_Pob_PROV.anio, INE_Pob_PROV.cod_serie, INE_Pob_PROV.nombre_serie_completo, INE_Pob_PROV.fuente, _meta.fecha_extraccion, _meta.cod_prov, _meta.capital, _meta.ccaa]
2026-08-20 19:52:42 | INFO    |
2026-08-20 19:52:42 | INFO    | =================================================================
2026-08-20 19:52:42 | INFO    |   FASE 2 · Censo Oficial de los 8.138 Municipios de España (INE Tabla 29005)
2026-08-20 19:52:42 | INFO    | =================================================================
2026-08-20 19:52:42 | INFO    | [INE_Pob_MUN] ▶ Descargando cifras oficiales del padrón de todos los municipios de España (Tabla 29005)...
2026-08-20 19:52:45 | INFO    | [INE] ✔ Tabla 29005 descargada: 24414 series.
2026-08-20 19:52:45 | INFO    | [INE_Pob_MUN] ✔ 8132 municipios oficiales de España extraídos.
2026-08-20 19:52:45 | INFO    | [csv_writer] ✔  8132 filas guardadas → municipios_espana.csv  [columnas: INE_Pob_MUN.nombre_municipio, INE_Pob_MUN.poblacion_oficial, INE_Pob_MUN.anio, INE_Pob_MUN.cod_serie, INE_Pob_MUN.nombre_serie_completo, INE_Pob_MUN.fuente, _meta.fecha_extraccion]
2026-08-20 19:52:45 | INFO    |
2026-08-20 19:52:45 | INFO    | =================================================================
2026-08-20 19:52:45 | INFO    |   FASE 3 · Flujos Turísticos EOH por Provincias y CCAA de España (INE Tabla 2074)
2026-08-20 19:52:45 | INFO    | =================================================================
2026-08-20 19:52:45 | INFO    | [INE_EOH_PROV] ▶ Descargando viajeros/pernoctaciones para todas las provincias y CCAA de España (últimos 12 períodos)...
2026-08-20 19:52:48 | INFO    | [INE] ✔ Tabla 2074 descargada: 420 series.
2026-08-20 19:52:48 | INFO    | [INE_EOH_PROV] ✔ 5040 filas | 69 ámbitos (todas las provincias y CCAA) | Tabla ID 2074
2026-08-20 19:52:48 | INFO    | [csv_writer] ✔  5040 filas guardadas → flujo_ine_provincia.csv  [columnas: INE_EOH_PROV.ambito, INE_EOH_PROV.indicador, INE_EOH_PROV.residencia, INE_EOH_PROV.nombre_serie_completo, INE_EOH_PROV.cod_serie, INE_EOH_PROV.anio, INE_EOH_PROV.periodo, INE_EOH_PROV.valor, INE_EOH_PROV.fuente, INE_EOH_PROV.tabla_id, _meta.fecha_extraccion]
2026-08-20 19:52:48 | INFO    |
2026-08-20 19:52:48 | INFO    | =================================================================
2026-08-20 19:52:48 | INFO    |   FASE 4 · Flujos Turísticos EOH por Localidad Turística (113 Puntos) (INE Tabla 2078)
2026-08-20 19:52:48 | INFO    | =================================================================
2026-08-20 19:52:48 | INFO    | [INE_EOH_MUN] ▶ Descargando viajeros/pernoctaciones por localidad turística (últimos 12 períodos)...
2026-08-20 19:52:52 | INFO    | [INE] ✔ Tabla 2078 descargada: 552 series.
2026-08-20 19:52:52 | INFO    | [INE_EOH_MUN] ✔ 6610 filas | 113 localidades turísticas | Tabla ID 2078
2026-08-20 19:52:52 | INFO    | [csv_writer] ✔  6610 filas guardadas → flujo_ine_localidad.csv  [columnas: INE_EOH_MUN.punto_turistico, INE_EOH_MUN.indicador, INE_EOH_MUN.residencia, INE_EOH_MUN.nombre_serie_completo, INE_EOH_MUN.cod_serie, INE_EOH_MUN.anio, INE_EOH_MUN.periodo, INE_EOH_MUN.valor, INE_EOH_MUN.fuente, INE_EOH_MUN.tabla_id, _meta.fecha_extraccion]
2026-08-20 19:52:52 | INFO    |
2026-08-20 19:52:52 | INFO    | =================================================================
2026-08-20 19:52:52 | INFO    |   FASE 5 · Geocodificación oficial CartoCiudad/IGN de Capitales y Puntos Clave
2026-08-20 19:52:52 | INFO    | =================================================================

Geocodificando Provincias:   0%|          | 0/52 [00:00<?, ?it/s]

2026-08-20 19:52:54 | INFO    | [CartoCiudad] ✔ Vitoria-Gasteiz → cod_ine=01059, prov=Araba/Álava, lat=42.8506, lon=-2.6614

Geocodificando Provincias:   2%|▏         | 1/52 [00:01<01:15,  1.49s/it]

2026-08-20 19:52:55 | INFO    | [CartoCiudad] ✔ Albacete → cod_ine=02003, prov=Albacete, lat=38.9951, lon=-1.8559

Geocodificando Provincias:   4%|▍         | 2/52 [00:03<01:22,  1.65s/it]

2026-08-20 19:52:57 | INFO    | [CartoCiudad] ✔ Alicante → cod_ine=03014, prov=Alacant/Alicante, lat=38.3436, lon=-0.4882

Geocodificando Provincias:   6%|▌         | 3/52 [00:05<01:28,  1.80s/it]

2026-08-20 19:53:00 | INFO    | [CartoCiudad] ✔ Almería → cod_ine=04013, prov=Almería, lat=36.8686, lon=-2.3120

Geocodificando Provincias:   8%|▊         | 4/52 [00:07<01:41,  2.12s/it]

2026-08-20 19:53:02 | INFO    | [CartoCiudad] ✔ Ávila → cod_ine=05019, prov=Ávila, lat=40.6572, lon=-4.6627

Geocodificando Provincias:  10%|▉         | 5/52 [00:09<01:30,  1.92s/it]

2026-08-20 19:53:04 | INFO    | [CartoCiudad] ✔ Badajoz → cod_ine=06015, prov=Badajoz, lat=38.8782, lon=-6.9701

Geocodificando Provincias:  12%|█▏        | 6/52 [00:11<01:33,  2.04s/it]

2026-08-20 19:53:06 | INFO    | [CartoCiudad] ✔ Palma → cod_ine=35016, prov=Las Palmas, lat=39.5696, lon=2.6501

Geocodificando Provincias:  13%|█▎        | 7/52 [00:13<01:29,  1.98s/it]

2026-08-20 19:53:07 | INFO    | [CartoCiudad] ✔ Barcelona → cod_ine=08019, prov=Barcelona, lat=41.3826, lon=2.1771

Geocodificando Provincias:  15%|█▌        | 8/52 [00:15<01:20,  1.82s/it]

2026-08-20 19:53:10 | INFO    | [CartoCiudad] ✔ Burgos → cod_ine=09059, prov=Burgos, lat=42.3448, lon=-3.6812

Geocodificando Provincias:  17%|█▋        | 9/52 [00:17<01:33,  2.17s/it]

2026-08-20 19:53:12 | INFO    | [CartoCiudad] ✔ Cáceres → cod_ine=10037, prov=Cáceres, lat=39.4745, lon=-6.3717

Geocodificando Provincias:  19%|█▉        | 10/52 [00:19<01:22,  1.96s/it]

2026-08-20 19:53:14 | INFO    | [CartoCiudad] ✔ Cádiz → cod_ine=11012, prov=Cádiz, lat=36.5297, lon=-6.2929

Geocodificando Provincias:  21%|██        | 11/52 [00:21<01:24,  2.07s/it]

2026-08-20 19:53:16 | INFO    | [CartoCiudad] ✔ Castellón de la Plana → cod_ine=12040, prov=Castelló/Castellón, lat=39.9860, lon=-0.0377

Geocodificando Provincias:  23%|██▎       | 12/52 [00:23<01:16,  1.91s/it]

2026-08-20 19:53:18 | INFO    | [CartoCiudad] ✔ Ciudad Real → cod_ine=13034, prov=Ciudad Real, lat=38.9597, lon=-3.8829

Geocodificando Provincias:  25%|██▌       | 13/52 [00:25<01:22,  2.11s/it]

2026-08-20 19:53:20 | INFO    | [CartoCiudad] ✔ Córdoba → cod_ine=14021, prov=Córdoba, lat=37.8846, lon=-4.7760

Geocodificando Provincias:  27%|██▋       | 14/52 [00:27<01:13,  1.92s/it]

2026-08-20 19:53:22 | INFO    | [CartoCiudad] ✔ A Coruña → cod_ine=15030, prov=A Coruña, lat=43.3466, lon=-8.4127

Geocodificando Provincias:  29%|██▉       | 15/52 [00:29<01:16,  2.07s/it]

2026-08-20 19:53:24 | INFO    | [CartoCiudad] ✔ Cuenca → cod_ine=16078, prov=Cuenca, lat=40.0661, lon=-2.1314

Geocodificando Provincias:  31%|███       | 16/52 [00:31<01:08,  1.91s/it]

2026-08-20 19:53:26 | INFO    | [CartoCiudad] ✔ Girona → cod_ine=17079, prov=Girona, lat=41.9793, lon=2.8199

Geocodificando Provincias:  33%|███▎      | 17/52 [00:33<01:07,  1.93s/it]

2026-08-20 19:53:28 | INFO    | [CartoCiudad] ✔ Granada → cod_ine=18087, prov=Granada, lat=37.1735, lon=-3.5995

Geocodificando Provincias:  35%|███▍      | 18/52 [00:35<01:07,  2.00s/it]

2026-08-20 19:53:29 | INFO    | [CartoCiudad] ✔ Guadalajara → cod_ine=19130, prov=Guadalajara, lat=40.7400, lon=-2.5059

Geocodificando Provincias:  37%|███▋      | 19/52 [00:37<01:04,  1.94s/it]

2026-08-20 19:53:32 | INFO    | [CartoCiudad] ✔ Donostia/San Sebastián → cod_ine=20069, prov=Gipuzkoa, lat=43.3224, lon=-1.9839

Geocodificando Provincias:  38%|███▊      | 20/52 [00:39<01:03,  1.99s/it]

2026-08-20 19:53:34 | INFO    | [CartoCiudad] ✔ Huelva → cod_ine=21041, prov=Huelva, lat=37.2576, lon=-6.9485

Geocodificando Provincias:  40%|████      | 21/52 [00:41<01:01,  1.97s/it]

2026-08-20 19:53:35 | INFO    | [CartoCiudad] ✔ Huesca → cod_ine=22125, prov=Huesca, lat=42.1361, lon=-0.0298

Geocodificando Provincias:  42%|████▏     | 22/52 [00:43<00:59,  1.97s/it]

2026-08-20 19:53:38 | INFO    | [CartoCiudad] ✔ Jaén → cod_ine=23050, prov=Jaén, lat=37.7729, lon=-3.7883

Geocodificando Provincias:  44%|████▍     | 23/52 [00:45<01:02,  2.16s/it]

2026-08-20 19:53:40 | INFO    | [CartoCiudad] ✔ León → cod_ine=24089, prov=León, lat=42.6341, lon=-5.9714

Geocodificando Provincias:  46%|████▌     | 24/52 [00:47<00:54,  1.96s/it]

2026-08-20 19:53:42 | INFO    | [CartoCiudad] ✔ Lleida → cod_ine=25120, prov=Lleida, lat=41.6148, lon=0.6268

Geocodificando Provincias:  48%|████▊     | 25/52 [00:49<00:53,  1.96s/it]

2026-08-20 19:53:44 | INFO    | [CartoCiudad] ✔ Logroño → cod_ine=26089, prov=La Rioja, lat=42.4661, lon=-2.4397

Geocodificando Provincias:  50%|█████     | 26/52 [00:51<00:51,  1.98s/it]

2026-08-20 19:53:46 | INFO    | [CartoCiudad] ✔ Lugo → cod_ine=27028, prov=Lugo, lat=43.0395, lon=-7.4568

Geocodificando Provincias:  52%|█████▏    | 27/52 [00:53<00:49,  1.99s/it]

2026-08-20 19:53:48 | INFO    | [CartoCiudad] ✔ Madrid → cod_ine=28079, prov=Madrid, lat=40.4168, lon=-3.7035

Geocodificando Provincias:  54%|█████▍    | 28/52 [00:55<00:49,  2.05s/it]

2026-08-20 19:53:50 | INFO    | [CartoCiudad] ✔ Málaga → cod_ine=29067, prov=Málaga, lat=36.7648, lon=-4.4422

Geocodificando Provincias:  56%|█████▌    | 29/52 [00:57<00:46,  2.01s/it]

2026-08-20 19:53:52 | INFO    | [CartoCiudad] ✔ Murcia → cod_ine=30030, prov=Murcia, lat=37.9348, lon=-1.1131

Geocodificando Provincias:  58%|█████▊    | 30/52 [00:59<00:43,  1.98s/it]

2026-08-20 19:53:54 | INFO    | [CartoCiudad] ✔ Pamplona/Iruña → cod_ine=31201, prov=Navarra, lat=42.8157, lon=-1.6522

Geocodificando Provincias:  60%|█████▉    | 31/52 [01:01<00:43,  2.08s/it]

2026-08-20 19:53:56 | INFO    | [CartoCiudad] ✔ Ourense → cod_ine=32054, prov=Ourense, lat=42.1940, lon=-7.5371

Geocodificando Provincias:  62%|██████▏   | 32/52 [01:03<00:38,  1.95s/it]

2026-08-20 19:53:58 | INFO    | [CartoCiudad] ✔ Oviedo → cod_ine=33044, prov=Asturias, lat=43.3533, lon=-5.8795

Geocodificando Provincias:  63%|██████▎   | 33/52 [01:05<00:37,  1.99s/it]

2026-08-20 19:54:00 | INFO    | [CartoCiudad] ✔ Palencia → cod_ine=34120, prov=Palencia, lat=42.4096, lon=-4.6161

Geocodificando Provincias:  65%|██████▌   | 34/52 [01:07<00:35,  1.95s/it]

2026-08-20 19:54:02 | INFO    | [CartoCiudad] ✔ Las Palmas de Gran Canaria → cod_ine=35016, prov=Las Palmas, lat=28.1289, lon=-15.4349

Geocodificando Provincias:  67%|██████▋   | 35/52 [01:09<00:33,  1.98s/it]

2026-08-20 19:54:03 | INFO    | [CartoCiudad] ✔ Pontevedra → cod_ine=36038, prov=Pontevedra, lat=42.4281, lon=-8.6041

Geocodificando Provincias:  69%|██████▉   | 36/52 [01:11<00:31,  1.97s/it]

2026-08-20 19:54:06 | INFO    | [CartoCiudad] ✔ Salamanca → cod_ine=37274, prov=Salamanca, lat=40.9652, lon=-5.6640

Geocodificando Provincias:  71%|███████   | 37/52 [01:13<00:30,  2.02s/it]

2026-08-20 19:54:07 | INFO    | [CartoCiudad] ✔ Santa Cruz de Tenerife → cod_ine=38038, prov=Santa Cruz de Tenerife, lat=28.4672, lon=-16.2508

Geocodificando Provincias:  73%|███████▎  | 38/52 [01:15<00:26,  1.91s/it]

2026-08-20 19:54:10 | INFO    | [CartoCiudad] ✔ Santander → cod_ine=39075, prov=Cantabria, lat=43.4619, lon=-3.8100

Geocodificando Provincias:  75%|███████▌  | 39/52 [01:17<00:26,  2.07s/it]

2026-08-20 19:54:12 | INFO    | [CartoCiudad] ✔ Segovia → cod_ine=40194, prov=Segovia, lat=40.9481, lon=-4.1172

Geocodificando Provincias:  77%|███████▋  | 40/52 [01:19<00:25,  2.14s/it]

2026-08-20 19:54:14 | INFO    | [CartoCiudad] ✔ Sevilla → cod_ine=41091, prov=Sevilla, lat=37.3886, lon=-5.9953

Geocodificando Provincias:  79%|███████▉  | 41/52 [01:21<00:21,  1.99s/it]

2026-08-20 19:54:16 | INFO    | [CartoCiudad] ✔ Soria → cod_ine=42173, prov=Soria, lat=41.6013, lon=-2.7219

Geocodificando Provincias:  81%|████████  | 42/52 [01:23<00:20,  2.02s/it]

2026-08-20 19:54:18 | INFO    | [CartoCiudad] ✔ Tarragona → cod_ine=43148, prov=Tarragona, lat=41.1172, lon=1.2546

Geocodificando Provincias:  83%|████████▎ | 43/52 [01:25<00:18,  2.09s/it]

2026-08-20 19:54:20 | INFO    | [CartoCiudad] ✔ Teruel → cod_ine=44216, prov=Teruel, lat=40.6005, lon=-0.9229

Geocodificando Provincias:  85%|████████▍ | 44/52 [01:27<00:15,  1.93s/it]

2026-08-20 19:54:22 | INFO    | [CartoCiudad] ✔ Toledo → cod_ine=45168, prov=Toledo, lat=39.8559, lon=-4.0243

Geocodificando Provincias:  87%|████████▋ | 45/52 [01:29<00:13,  1.95s/it]

2026-08-20 19:54:24 | INFO    | [CartoCiudad] ✔ València → cod_ine=46250, prov=València/Valencia, lat=39.4697, lon=-0.3763

Geocodificando Provincias:  88%|████████▊ | 46/52 [01:31<00:12,  2.00s/it]

2026-08-20 19:54:26 | INFO    | [CartoCiudad] ✔ Valladolid → cod_ine=47186, prov=Valladolid, lat=41.6200, lon=-4.7260

Geocodificando Provincias:  90%|█████████ | 47/52 [01:33<00:09,  1.97s/it]

2026-08-20 19:54:28 | INFO    | [CartoCiudad] ✔ Bilbao → cod_ine=48020, prov=Bizkaia, lat=43.2630, lon=-2.9350

Geocodificando Provincias:  92%|█████████▏| 48/52 [01:35<00:08,  2.14s/it]

2026-08-20 19:54:30 | INFO    | [CartoCiudad] ✔ Zamora → cod_ine=49275, prov=Zamora, lat=41.6858, lon=-5.9423

Geocodificando Provincias:  94%|█████████▍| 49/52 [01:37<00:06,  2.04s/it]

2026-08-20 19:54:32 | INFO    | [CartoCiudad] ✔ Zaragoza → cod_ine=50297, prov=Zaragoza, lat=41.6916, lon=-0.9101

Geocodificando Provincias:  96%|█████████▌| 50/52 [01:39<00:04,  2.04s/it]

2026-08-20 19:54:33 | INFO    | [CartoCiudad] ✔ Ceuta → cod_ine=51001, prov=Ceuta, lat=35.8944, lon=-5.3558

Geocodificando Provincias:  98%|█████████▊| 51/52 [01:41<00:01,  1.86s/it]

2026-08-20 19:54:35 | INFO    | [CartoCiudad] ✔ Melilla → cod_ine=52001, prov=Melilla, lat=35.2919, lon=-2.9409

Geocodificando Provincias: 100%|██████████| 52/52 [01:43<00:00,  1.99s/it]

2026-08-20 19:54:35 | INFO    | [csv_writer] ✔  52 filas guardadas → localidades.csv  [columnas: CartoCiudad.cod_ine, CartoCiudad.nombre_municipio, CartoCiudad.provincia, CartoCiudad.ccaa, CartoCiudad.latitud, CartoCiudad.longitud, _meta.fuente_geocod, _meta.fecha_extraccion, _meta.cod_ine_clave, _meta.nombre_municipio]
2026-08-20 19:54:35 | INFO    |
2026-08-20 19:54:35 | INFO    | =================================================================
2026-08-20 19:54:35 | INFO    |   FASE 6 · Oferta Turística de Capitales (OSM Overpass — POIs)
2026-08-20 19:54:35 | INFO    | =================================================================

POIs OSM:   0%|          | 0/52 [00:00<?, ?it/s]

2026-08-20 19:54:47 | INFO    | [OSM] ↪ Overpass no disponible para 'Vitoria-Gasteiz'; usando fallback Nominatim...
2026-08-20 19:54:51 | INFO    | [OSM] ✔ Vitoria-Gasteiz (Fallback Nominatim) → hoteles=32, restaurantes=50, atracciones=0, museos=16

POIs OSM:   2%|▏         | 1/52 [00:15<13:34, 15.97s/it]

2026-08-20 19:55:01 | INFO    | [OSM] ✔ Albacete → hoteles=11, restaurantes=132, atracciones=2, museos=6 [vía Overpass (overpass-api.de)]

POIs OSM:   4%|▍         | 2/52 [00:25<10:01, 12.03s/it]

2026-08-20 19:55:12 | INFO    | [OSM] ✔ Alicante → hoteles=55, restaurantes=523, atracciones=14, museos=13 [vía Overpass (maps.mail.ru)]

POIs OSM:   6%|▌         | 3/52 [00:36<09:28, 11.60s/it]

2026-08-20 19:55:21 | INFO    | [OSM] ↪ Overpass no disponible para 'Almería'; usando fallback Nominatim...
2026-08-20 19:55:26 | INFO    | [OSM] ✔ Almería (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=50

POIs OSM:   8%|▊         | 4/52 [00:50<10:04, 12.60s/it]

2026-08-20 19:55:37 | INFO    | [OSM] ↪ Overpass no disponible para 'Ávila'; usando fallback Nominatim...
2026-08-20 19:55:42 | INFO    | [OSM] ✔ Ávila (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=8, museos=20

POIs OSM:  10%|▉         | 5/52 [01:06<10:51, 13.86s/it]

2026-08-20 19:55:58 | INFO    | [OSM] ↪ Overpass no disponible para 'Badajoz'; usando fallback Nominatim...
2026-08-20 19:56:04 | INFO    | [OSM] ✔ Badajoz (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=31

POIs OSM:  12%|█▏        | 6/52 [01:28<12:41, 16.56s/it]

2026-08-20 19:56:13 | INFO    | [OSM] ✔ Palma → hoteles=139, restaurantes=614, atracciones=22, museos=13 [vía Overpass (overpass-api.de)]

POIs OSM:  13%|█▎        | 7/52 [01:37<10:38, 14.20s/it]

2026-08-20 19:56:23 | INFO    | [OSM] ✔ Barcelona → hoteles=511, restaurantes=4040, atracciones=101, museos=90 [vía Overpass (overpass-api.de)]

POIs OSM:  15%|█▌        | 8/52 [01:47<09:27, 12.91s/it]

2026-08-20 19:56:37 | INFO    | [OSM] ↪ Overpass no disponible para 'Burgos'; usando fallback Nominatim...
2026-08-20 19:56:44 | INFO    | [OSM] ✔ Burgos (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=44, museos=50

POIs OSM:  17%|█▋        | 9/52 [02:08<11:04, 15.46s/it]

2026-08-20 19:56:59 | INFO    | [OSM] ↪ Overpass no disponible para 'Cáceres'; usando fallback Nominatim...
2026-08-20 19:57:05 | INFO    | [OSM] ✔ Cáceres (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=50

POIs OSM:  19%|█▉        | 10/52 [02:29<12:00, 17.15s/it]

2026-08-20 19:57:20 | INFO    | [OSM] ↪ Overpass no disponible para 'Cádiz'; usando fallback Nominatim...
2026-08-20 19:57:25 | INFO    | [OSM] ✔ Cádiz (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=50

POIs OSM:  21%|██        | 11/52 [02:49<12:19, 18.04s/it]

2026-08-20 19:57:37 | INFO    | [OSM] ↪ Overpass no disponible para 'Castellón de la Plana'; usando fallback Nominatim...
2026-08-20 19:57:41 | INFO    | [OSM] ✔ Castellón de la Plana (Fallback Nominatim) → hoteles=14, restaurantes=50, atracciones=0, museos=6

POIs OSM:  23%|██▎       | 12/52 [03:05<11:35, 17.38s/it]

2026-08-20 19:57:50 | INFO    | [OSM] ✔ Ciudad Real → hoteles=11, restaurantes=19, atracciones=2, museos=6 [vía Overpass (overpass-api.de)]

POIs OSM:  25%|██▌       | 13/52 [03:14<09:31, 14.66s/it]

2026-08-20 19:57:58 | INFO    | [OSM] ✔ Córdoba → hoteles=70, restaurantes=356, atracciones=52, museos=18 [vía Overpass (overpass-api.de)]

POIs OSM:  27%|██▋       | 14/52 [03:22<08:04, 12.76s/it]

2026-08-20 19:58:13 | INFO    | [OSM] ↪ Overpass no disponible para 'A Coruña'; usando fallback Nominatim...
2026-08-20 19:58:19 | INFO    | [OSM] ✔ A Coruña (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=50

POIs OSM:  29%|██▉       | 15/52 [03:43<09:19, 15.13s/it]

2026-08-20 19:58:34 | INFO    | [OSM] ↪ Overpass no disponible para 'Cuenca'; usando fallback Nominatim...
2026-08-20 19:58:39 | INFO    | [OSM] ✔ Cuenca (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=48

POIs OSM:  31%|███       | 16/52 [04:03<10:04, 16.78s/it]

2026-08-20 19:58:52 | INFO    | [OSM] ✔ Girona → hoteles=37, restaurantes=329, atracciones=8, museos=11 [vía Overpass (overpass-api.de)]

POIs OSM:  33%|███▎      | 17/52 [04:16<09:02, 15.50s/it]

2026-08-20 19:59:06 | INFO    | [OSM] ↪ Overpass no disponible para 'Granada'; usando fallback Nominatim...
2026-08-20 19:59:14 | INFO    | [OSM] ✔ Granada (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=50

POIs OSM:  35%|███▍      | 18/52 [04:38<09:57, 17.57s/it]

2026-08-20 19:59:29 | INFO    | [OSM] ↪ Overpass no disponible para 'Guadalajara'; usando fallback Nominatim...
2026-08-20 19:59:36 | INFO    | [OSM] ✔ Guadalajara (Fallback Nominatim) → hoteles=50, restaurantes=47, atracciones=0, museos=47

POIs OSM:  37%|███▋      | 19/52 [05:00<10:24, 18.93s/it]

2026-08-20 19:59:51 | INFO    | [OSM] ↪ Overpass no disponible para 'Donostia/San Sebastián'; usando fallback Nominatim...
2026-08-20 19:59:55 | INFO    | [OSM] ✔ Donostia/San Sebastián (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=11

POIs OSM:  38%|███▊      | 20/52 [05:19<10:06, 18.97s/it]

2026-08-20 20:00:05 | INFO    | [OSM] ✔ Huelva → hoteles=9, restaurantes=85, atracciones=15, museos=5 [vía Overpass (overpass-api.de)]

POIs OSM:  40%|████      | 21/52 [05:29<08:22, 16.21s/it]

2026-08-20 20:00:15 | INFO    | [OSM] ✔ Huesca → hoteles=7, restaurantes=12, atracciones=1, museos=1 [vía Overpass (overpass-api.de)]

POIs OSM:  42%|████▏     | 22/52 [05:39<07:06, 14.22s/it]

2026-08-20 20:00:30 | INFO    | [OSM] ↪ Overpass no disponible para 'Jaén'; usando fallback Nominatim...
2026-08-20 20:00:34 | INFO    | [OSM] ✔ Jaén (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=50

POIs OSM:  44%|████▍     | 23/52 [05:58<07:39, 15.86s/it]

2026-08-20 20:00:49 | INFO    | [OSM] ↪ Overpass no disponible para 'León'; usando fallback Nominatim...
2026-08-20 20:00:56 | INFO    | [OSM] ✔ León (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=50, museos=45

POIs OSM:  46%|████▌     | 24/52 [06:20<08:09, 17.49s/it]

2026-08-20 20:01:06 | INFO    | [OSM] ✔ Lleida → hoteles=15, restaurantes=194, atracciones=3, museos=9 [vía Overpass (overpass-api.de)]

POIs OSM:  48%|████▊     | 25/52 [06:30<06:54, 15.33s/it]

2026-08-20 20:01:18 | INFO    | [OSM] ↪ Overpass no disponible para 'Logroño'; usando fallback Nominatim...
2026-08-20 20:01:22 | INFO    | [OSM] ✔ Logroño (Fallback Nominatim) → hoteles=33, restaurantes=50, atracciones=0, museos=8

POIs OSM:  50%|█████     | 26/52 [06:47<06:48, 15.70s/it]

2026-08-20 20:01:38 | INFO    | [OSM] ↪ Overpass no disponible para 'Lugo'; usando fallback Nominatim...
2026-08-20 20:01:43 | INFO    | [OSM] ✔ Lugo (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=44

POIs OSM:  52%|█████▏    | 27/52 [07:07<07:09, 17.17s/it]

2026-08-20 20:01:56 | INFO    | [OSM] ↪ Overpass no disponible para 'Madrid'; usando fallback Nominatim...
2026-08-20 20:02:04 | INFO    | [OSM] ✔ Madrid (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=1, museos=50

POIs OSM:  54%|█████▍    | 28/52 [07:28<07:18, 18.25s/it]

2026-08-20 20:02:14 | INFO    | [OSM] ✔ Málaga → hoteles=94, restaurantes=543, atracciones=39, museos=37 [vía Overpass (overpass-api.de)]

POIs OSM:  56%|█████▌    | 29/52 [07:39<06:06, 15.95s/it]

2026-08-20 20:02:23 | INFO    | [OSM] ✔ Murcia → hoteles=21, restaurantes=180, atracciones=16, museos=17 [vía Overpass (overpass-api.de)]

POIs OSM:  58%|█████▊    | 30/52 [07:47<04:59, 13.62s/it]

2026-08-20 20:02:35 | INFO    | [OSM] ↪ Overpass no disponible para 'Pamplona/Iruña'; usando fallback Nominatim...
2026-08-20 20:02:40 | INFO    | [OSM] ✔ Pamplona/Iruña (Fallback Nominatim) → hoteles=44, restaurantes=50, atracciones=0, museos=9

POIs OSM:  60%|█████▉    | 31/52 [08:04<05:09, 14.73s/it]

2026-08-20 20:02:55 | INFO    | [OSM] ↪ Overpass no disponible para 'Ourense'; usando fallback Nominatim...
2026-08-20 20:03:00 | INFO    | [OSM] ✔ Ourense (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=44

POIs OSM:  62%|██████▏   | 32/52 [08:24<05:24, 16.21s/it]

2026-08-20 20:03:14 | INFO    | [OSM] ↪ Overpass no disponible para 'Oviedo'; usando fallback Nominatim...
2026-08-20 20:03:19 | INFO    | [OSM] ✔ Oviedo (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=12

POIs OSM:  63%|██████▎   | 33/52 [08:43<05:27, 17.24s/it]

2026-08-20 20:03:28 | INFO    | [OSM] ✔ Palencia → hoteles=2, restaurantes=4, atracciones=2, museos=1 [vía Overpass (overpass-api.de)]

POIs OSM:  65%|██████▌   | 34/52 [08:52<04:23, 14.65s/it]

2026-08-20 20:03:38 | INFO    | [OSM] ✔ Las Palmas de Gran Canaria → hoteles=72, restaurantes=478, atracciones=26, museos=8 [vía Overpass (overpass-api.de)]

POIs OSM:  67%|██████▋   | 35/52 [09:02<03:44, 13.22s/it]

2026-08-20 20:03:53 | INFO    | [OSM] ↪ Overpass no disponible para 'Pontevedra'; usando fallback Nominatim...
2026-08-20 20:03:58 | INFO    | [OSM] ✔ Pontevedra (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=50

POIs OSM:  69%|██████▉   | 36/52 [09:22<04:03, 15.21s/it]

2026-08-20 20:04:11 | INFO    | [OSM] ✔ Salamanca → hoteles=46, restaurantes=248, atracciones=26, museos=15 [vía Overpass (maps.mail.ru)]

POIs OSM:  71%|███████   | 37/52 [09:35<03:39, 14.61s/it]

2026-08-20 20:04:26 | INFO    | [OSM] ↪ Overpass no disponible para 'Santa Cruz de Tenerife'; usando fallback Nominatim...
2026-08-20 20:04:31 | INFO    | [OSM] ✔ Santa Cruz de Tenerife (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=50

POIs OSM:  73%|███████▎  | 38/52 [09:55<03:49, 16.40s/it]

2026-08-20 20:04:41 | INFO    | [OSM] ✔ Santander → hoteles=69, restaurantes=316, atracciones=13, museos=25 [vía Overpass (overpass-api.de)]

POIs OSM:  75%|███████▌  | 39/52 [10:05<03:04, 14.22s/it]

2026-08-20 20:04:53 | INFO    | [OSM] ✔ Segovia → hoteles=53, restaurantes=96, atracciones=115, museos=15 [vía Overpass (maps.mail.ru)]

POIs OSM:  77%|███████▋  | 40/52 [10:17<02:45, 13.76s/it]

2026-08-20 20:05:08 | INFO    | [OSM] ↪ Overpass no disponible para 'Sevilla'; usando fallback Nominatim...
2026-08-20 20:05:16 | INFO    | [OSM] ✔ Sevilla (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=50

POIs OSM:  79%|███████▉  | 41/52 [10:40<03:00, 16.41s/it]

2026-08-20 20:05:31 | INFO    | [OSM] ↪ Overpass no disponible para 'Soria'; usando fallback Nominatim...
2026-08-20 20:05:36 | INFO    | [OSM] ✔ Soria (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=8, museos=50

POIs OSM:  81%|████████  | 42/52 [11:00<02:56, 17.67s/it]

2026-08-20 20:05:51 | INFO    | [OSM] ↪ Overpass no disponible para 'Tarragona'; usando fallback Nominatim...
2026-08-20 20:05:57 | INFO    | [OSM] ✔ Tarragona (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=50

POIs OSM:  83%|████████▎ | 43/52 [11:21<02:47, 18.59s/it]

2026-08-20 20:06:12 | INFO    | [OSM] ↪ Overpass no disponible para 'Teruel'; usando fallback Nominatim...
2026-08-20 20:06:16 | INFO    | [OSM] ✔ Teruel (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=44

POIs OSM:  85%|████████▍ | 44/52 [11:40<02:30, 18.77s/it]

2026-08-20 20:06:31 | INFO    | [OSM] ↪ Overpass no disponible para 'Toledo'; usando fallback Nominatim...
2026-08-20 20:06:37 | INFO    | [OSM] ✔ Toledo (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=50

POIs OSM:  87%|████████▋ | 45/52 [12:01<02:14, 19.26s/it]

2026-08-20 20:06:51 | INFO    | [OSM] ↪ Overpass no disponible para 'València'; usando fallback Nominatim...
2026-08-20 20:06:58 | INFO    | [OSM] ✔ València (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=2, museos=50

POIs OSM:  88%|████████▊ | 46/52 [12:22<01:58, 19.76s/it]

2026-08-20 20:07:12 | INFO    | [OSM] ↪ Overpass no disponible para 'Valladolid'; usando fallback Nominatim...
2026-08-20 20:07:18 | INFO    | [OSM] ✔ Valladolid (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=20, museos=46

POIs OSM:  90%|█████████ | 47/52 [12:42<01:39, 19.91s/it]

2026-08-20 20:07:33 | INFO    | [OSM] ↪ Overpass no disponible para 'Bilbao'; usando fallback Nominatim...
2026-08-20 20:07:38 | INFO    | [OSM] ✔ Bilbao (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=1, museos=50

POIs OSM:  92%|█████████▏| 48/52 [13:02<01:20, 20.09s/it]

2026-08-20 20:07:53 | INFO    | [OSM] ✔ Zamora → hoteles=0, restaurantes=0, atracciones=0, museos=1 [vía Overpass (maps.mail.ru)]

POIs OSM:  94%|█████████▍| 49/52 [13:17<00:54, 18.30s/it]

2026-08-20 20:08:07 | INFO    | [OSM] ↪ Overpass no disponible para 'Zaragoza'; usando fallback Nominatim...
2026-08-20 20:08:13 | INFO    | [OSM] ✔ Zaragoza (Fallback Nominatim) → hoteles=50, restaurantes=50, atracciones=0, museos=50

POIs OSM:  96%|█████████▌| 50/52 [13:37<00:37, 18.88s/it]

2026-08-20 20:08:28 | INFO    | [OSM] ↪ Overpass no disponible para 'Ceuta'; usando fallback Nominatim...
2026-08-20 20:08:31 | INFO    | [OSM] ✔ Ceuta (Fallback Nominatim) → hoteles=12, restaurantes=50, atracciones=0, museos=5

POIs OSM:  98%|█████████▊| 51/52 [13:55<00:18, 18.71s/it]

2026-08-20 20:08:43 | INFO    | [OSM] ↪ Overpass no disponible para 'Melilla'; usando fallback Nominatim...
2026-08-20 20:08:46 | INFO    | [OSM] ✔ Melilla (Fallback Nominatim) → hoteles=8, restaurantes=25, atracciones=0, museos=11

POIs OSM: 100%|██████████| 52/52 [14:10<00:00, 16.36s/it]

2026-08-20 20:08:46 | INFO    | [csv_writer] ✔  52 filas guardadas → oferta_osm.csv  [columnas: OSM_Overpass.num_hoteles, OSM_Overpass.num_restaurantes, OSM_Overpass.num_atracciones, OSM_Overpass.num_museos, OSM_Overpass.fuente, OSM_Overpass.fecha_extraccion, _meta.cod_ine_clave, _meta.nombre_municipio]
2026-08-20 20:08:46 | INFO    |
2026-08-20 20:08:46 | INFO    | =================================================================
2026-08-20 20:08:46 | INFO    |   FASE 7 · POIs TripAdvisor (requiere API key)
2026-08-20 20:08:46 | INFO    | =================================================================
2026-08-20 20:08:46 | WARNING | [TripAdvisor] ⊘ TRIPADVISOR_API_KEY no configurada. Define la clave en .env para activar este extractor.
2026-08-20 20:08:46 | WARNING | [reporter] ⊘  TripAdvisor omitido → TRIPADVISOR_API_KEY no configurada en .env. Solicita la clave en tripadvisor.com/developers.
2026-08-20 20:08:46 | INFO    |
2026-08-20 20:08:46 | INFO    | =================================================================
2026-08-20 20:08:46 | INFO    |   FASE 8 · Catálogo Nacional de Datasets Abiertos (datos.gob.es)
2026-08-20 20:08:46 | INFO    | =================================================================
2026-08-20 20:08:46 | INFO    | [DatosGob] ▶ Buscando datasets relacionados con 'turismo' en el catálogo nacional...

2026-08-20 20:08:47 | INFO    | [DatosGob] ✔ 'turismo' → 0 recursos encontrados en el catálogo.
2026-08-20 20:08:47 | WARNING | [reporter] ✗  DatosGob | turismo → Error: Búsqueda 'turismo' en datos.gob.es devolvió DataFrame vacío o error.
2026-08-20 20:08:47 | INFO    | [DatosGob] ▶ Buscando datasets relacionados con 'ocupación hotelera' en el catálogo nacional...
2026-08-20 20:08:48 | INFO    | [DatosGob] ✔ 'ocupación hotelera' → 0 recursos encontrados en el catálogo.
2026-08-20 20:08:48 | WARNING | [reporter] ✗  DatosGob | ocupación hotelera → Error: Búsqueda 'ocupación hotelera' en datos.gob.es devolvió DataFrame vacío o error.
2026-08-20 20:08:48 | INFO    | [DatosGob] ▶ Buscando datasets relacionados con 'turismo rural' en el catálogo nacional...
2026-08-20 20:08:48 | INFO    | [DatosGob] ✔ 'turismo rural' → 0 recursos encontrados en el catálogo.
2026-08-20 20:08:48 | WARNING | [reporter] ✗  DatosGob | turismo rural → Error: Búsqueda 'turismo rural' en datos.gob.es devolvió DataFrame vacío o error.
2026-08-20 20:08:48 | INFO    | [DatosGob] ▶ Buscando datasets relacionados con 'alojamientos turísticos' en el catálogo nacional...
2026-08-20 20:08:49 | INFO    | [DatosGob] ✔ 'alojamientos turísticos' → 0 recursos encontrados en el catálogo.
2026-08-20 20:08:49 | WARNING | [reporter] ✗  DatosGob | alojamientos turísticos → Error: Búsqueda 'alojamientos turísticos' en datos.gob.es devolvió DataFrame vacío o error.
2026-08-20 20:08:49 | INFO    |
2026-08-20 20:08:49 | INFO    | =================================================================
2026-08-20 20:08:49 | INFO    |   FASE 9 · Cierre del pipeline y Generación de Reporte
2026-08-20 20:08:49 | INFO    | =================================================================
2026-08-20 20:08:49 | WARNING | [reporter] ⚠  Reporte de fallos guardado (5 entradas) → reporte_fallos.csv

============================================================
  RESUMEN DE FALLOS DEL PIPELINE
============================================================
  [TripAdvisor] — — Omitido: TRIPADVISOR_API_KEY no configurada en .env. Solicita la clave en tripadvisor.com/developers.
  [DatosGob] turismo — Error: Búsqueda 'turismo' en datos.gob.es devolvió DataFrame vacío o error.
  [DatosGob] ocupación hotelera — Error: Búsqueda 'ocupación hotelera' en datos.gob.es devolvió DataFrame vacío o error.
  [DatosGob] turismo rural — Error: Búsqueda 'turismo rural' en datos.gob.es devolvió DataFrame vacío o error.
  [DatosGob] alojamientos turísticos — Error: Búsqueda 'alojamientos turísticos' en datos.gob.es devolvió DataFrame vacío o error.
============================================================
  Total fallos: 5
============================================================

2026-08-20 20:08:49 | INFO    | Pipeline nacional completado.
2026-08-20 20:08:49 | INFO    | Archivos CSV generados en: C:\Users\Manuel Santos\Escritorio\MASTER\TFM - TUI\Antigravity-Prueba\data\processed
2026-08-20 20:08:49 | INFO    | Log de sesión guardado en: C:\Users\Manuel Santos\Escritorio\MASTER\TFM - TUI\Antigravity-Prueba\data\logs\log_sesion_20260820_195242.txt

In [11]:
localidades = pd.read_csv('data/processed/flujo_ine_localidad.csv', sep=',', encoding='UTF-8')
provincias = pd.read_csv('data/processed/flujo_ine_provincia.csv', sep=',', encoding='UTF-8')
localidades_data = pd.read_csv('data/processed/localidades.csv', sep=',', encoding='UTF-8')
OpenStreetDf = pd.read_csv('data/processed/oferta_osm.csv', sep=',', encoding='UTF-8')
provincias_data = pd.read_csv('data/processed/municipios_espana.csv', sep=',', encoding='UTF-8')

In [12]:
localidades.head()

,INE_EOH_MUN.punto_turistico,INE_EOH_MUN.indicador,INE_EOH_MUN.residencia,INE_EOH_MUN.nombre_serie_completo,INE_EOH_MUN.cod_serie,INE_EOH_MUN.anio,INE_EOH_MUN.periodo,INE_EOH_MUN.valor,INE_EOH_MUN.fuente,INE_EOH_MUN.tabla_id,_meta.fecha_extraccion
0,Vitoria-Gastéiz,viajeros,Residentes en España,Nacional. Viajeros. Vitoria-Gastéiz. Residente...,EOT2611,2026,NaN,19464.0,INE_EOH_MUN,2078,2026-08-20T17:52:52.593070
1,Vitoria-Gastéiz,viajeros,Residentes en España,Nacional. Viajeros. Vitoria-Gastéiz. Residente...,EOT2611,2026,NaN,20574.0,INE_EOH_MUN,2078,2026-08-20T17:52:52.593070
2,Vitoria-Gastéiz,viajeros,Residentes en España,Nacional. Viajeros. Vitoria-Gastéiz. Residente...,EOT2611,2026,NaN,21012.0,INE_EOH_MUN,2078,2026-08-20T17:52:52.593070
3,Vitoria-Gastéiz,viajeros,Residentes en España,Nacional. Viajeros. Vitoria-Gastéiz. Residente...,EOT2611,2026,NaN,20189.0,INE_EOH_MUN,2078,2026-08-20T17:52:52.593070
4,Vitoria-Gastéiz,viajeros,Residentes en España,Nacional. Viajeros. Vitoria-Gastéiz. Residente...,EOT2611,2026,NaN,18573.0,INE_EOH_MUN,2078,2026-08-20T17:52:52.593070

In [13]:
localidades_data.head()

,CartoCiudad.cod_ine,CartoCiudad.nombre_municipio,CartoCiudad.provincia,CartoCiudad.ccaa,CartoCiudad.latitud,CartoCiudad.longitud,_meta.fuente_geocod,_meta.fecha_extraccion,_meta.cod_ine_clave,_meta.nombre_municipio
0,1059,Vitoria-Gasteiz,Araba/Álava,País Vasco/Euskadi,42.850584,-2.661450,CartoCiudad+IGN,2026-08-20T17:52:54.199537,1059,Vitoria-Gasteiz
1,2003,Albacete,Albacete,Castilla-La Mancha,38.995092,-1.855915,CartoCiudad+IGN,2026-08-20T17:52:55.964735,2003,Albacete
2,3014,Alacant/Alicante,Alacant/Alicante,Comunitat Valenciana,38.343637,-0.488171,CartoCiudad+IGN,2026-08-20T17:52:57.944869,3014,Alicante
3,4013,Almería,Almería,Andalucía,36.868574,-2.312028,CartoCiudad+IGN,2026-08-20T17:53:00.562414,4013,Almería
4,5019,Ávila,Ávila,Castilla y León,40.657195,-4.662668,CartoCiudad+IGN,2026-08-20T17:53:02.112215,5019,Ávila

In [14]:
provincias[provincias['INE_EOH_PROV.indicador']=='Viajero'].head()

,INE_EOH_PROV.ambito,INE_EOH_PROV.indicador,INE_EOH_PROV.residencia,INE_EOH_PROV.nombre_serie_completo,INE_EOH_PROV.cod_serie,INE_EOH_PROV.anio,INE_EOH_PROV.periodo,INE_EOH_PROV.valor,INE_EOH_PROV.fuente,INE_EOH_PROV.tabla_id,_meta.fecha_extraccion
1080,Asturias,Viajero,Total categorías,Asturias. Viajero. Total categorías. Total. Da...,EOT22203,2026,NaN,206637.0,INE_EOH_PROV,2074,2026-08-20T17:52:48.916769
1081,Asturias,Viajero,Total categorías,Asturias. Viajero. Total categorías. Total. Da...,EOT22203,2026,NaN,175443.0,INE_EOH_PROV,2074,2026-08-20T17:52:48.916769
1082,Asturias,Viajero,Total categorías,Asturias. Viajero. Total categorías. Total. Da...,EOT22203,2026,NaN,147543.0,INE_EOH_PROV,2074,2026-08-20T17:52:48.916769
1083,Asturias,Viajero,Total categorías,Asturias. Viajero. Total categorías. Total. Da...,EOT22203,2026,NaN,113361.0,INE_EOH_PROV,2074,2026-08-20T17:52:48.916769
1084,Asturias,Viajero,Total categorías,Asturias. Viajero. Total categorías. Total. Da...,EOT22203,2026,NaN,87964.0,INE_EOH_PROV,2074,2026-08-20T17:52:48.916769

In [15]:
provincias_data.head()

,INE_Pob_MUN.nombre_municipio,INE_Pob_MUN.poblacion_oficial,INE_Pob_MUN.anio,INE_Pob_MUN.cod_serie,INE_Pob_MUN.nombre_serie_completo,INE_Pob_MUN.fuente,_meta.fecha_extraccion
0,Ababuj,73.0,2025,DPOP19723,Ababuj. Total. Total habitantes. Personas.,INE_Padron_Tabla_29005,2026-08-20T17:52:45.013965
1,Abades,849.0,2025,DPOP17671,Abades. Total. Total habitantes. Personas.,INE_Padron_Tabla_29005,2026-08-20T17:52:45.013965
2,Abadía,337.0,2025,DPOP4663,Abadía. Total. Total habitantes. Personas.,INE_Padron_Tabla_29005,2026-08-20T17:52:45.013965
3,Abadín,2239.0,2025,DPOP12721,Abadín. Total. Total habitantes. Personas.,INE_Padron_Tabla_29005,2026-08-20T17:52:45.013965
4,Abadiño,7768.0,2025,DPOP22525,Abadiño. Total. Total habitantes. Personas.,INE_Padron_Tabla_29005,2026-08-20T17:52:45.013965

In [16]:
OpenStreetDf.head()

,OSM_Overpass.num_hoteles,OSM_Overpass.num_restaurantes,OSM_Overpass.num_atracciones,OSM_Overpass.num_museos,OSM_Overpass.fuente,OSM_Overpass.fecha_extraccion,_meta.cod_ine_clave,_meta.nombre_municipio
0,32,50,0,16,OSM_Nominatim_Fallback,2026-08-20T17:54:51.916705,1059,Vitoria-Gasteiz
1,11,132,2,6,Overpass (overpass-api.de),2026-08-20T17:55:01.199341,2003,Albacete
2,55,523,14,13,Overpass (maps.mail.ru),2026-08-20T17:55:12.282138,3014,Alicante
3,50,50,0,50,OSM_Nominatim_Fallback,2026-08-20T17:55:26.418242,4013,Almería
4,50,50,8,20,OSM_Nominatim_Fallback,2026-08-20T17:55:42.508956,5019,Ávila